#!/usr/bin/env dub
/+ dub.sdl:
    name "gen_grapheme_tables"
    dflags "-preview=in" "-preview=dip1000"
    buildType "checked" {
        buildOptions "optimize" "inline" "debugInfo"
    }
+/

/**
Generate the ordinary-starter boundary cache from the running compiler's public
Phobos grapheme engine. Probes run here, not during every consumer compilation.
Regenerate when updating the supported compiler/Phobos version; width.d's
exhaustive runtime parity test rejects stale data. Other frontend versions
retain the public engine rather than using this cache.

Usage: dub run --single libs/base/tools/gen_grapheme_tables.d -bchecked
An optional output path writes somewhere other than the in-tree module.
*/
module sparkles.base.tools.gen_grapheme_tables;

import std.array : appender;
import std.conv : text;
import std.file : write;
import std.path : buildNormalizedPath, dirName;
import std.range : put;
import std.uni : graphemeStride;

private enum uint cacheLimit = 0x20000;

int main(string[] args) @system
{
    auto output = appender!string;
    put(output, "/** Generated by libs/base/tools/gen_grapheme_tables.d; do not edit. */\n"
        ~ "module sparkles.base.text.grapheme_tables;\n\n"
        ~ text("package enum uint singletonCompilerVersion = ", __VERSION__, ";\n")
        ~ text("package enum uint singletonCacheLimit = ", cacheLimit, ";\n\n")
        ~ "package struct SingletonBoundaryRun\n{\n"
        ~ "    uint begin;\n    uint end;\n    ubyte traits;\n}\n\n"
        ~ "// Incoming attachment (bit 2); ordinary outgoing break (bit 6).\n"
        ~ "package immutable SingletonBoundaryRun[] singletonBoundaryRuns = [\n");
    uint begin;
    ubyte last;
    dchar[2] probe;
    foreach (uint cp; 0 .. cacheLimit)
    {
        probe[0] = 'a';
        probe[1] = cast(dchar) cp;
        ubyte traits = graphemeStride(probe[], 0) != 1 ? 4 : 0;
        probe[0] = cast(dchar) cp;
        probe[1] = 'a';
        if (graphemeStride(probe[], 0) == 1)
            traits |= 64;
        if (cp != 0 && traits != last)
        {
            put(output, text("    SingletonBoundaryRun(begin: ", begin,
                ", end: ", cp, ", traits: ", last, "),\n"));
            begin = cp;
        }
        last = traits;
    }
    put(output, text("    SingletonBoundaryRun(begin: ", begin,
        ", end: ", cacheLimit, ", traits: ", last, "),\n];\n"));
    const path = args.length > 1 ? args[1] : __FILE_FULL_PATH__.dirName
        .buildNormalizedPath("../src/sparkles/base/text/grapheme_tables.d");
    write(path, output.data);
    return 0;
}
