/**
 * Ed25519 → X25519 (Montgomery) key conversion (§6).
 *
 * `age` reuses an existing `ssh-ed25519` host/user key as an age recipient by
 * mapping the Ed25519 (twisted Edwards) key pair onto the birationally
 * equivalent Curve25519 (Montgomery) key pair, then running the standard
 * X25519 recipient handshake. These two free functions expose that mapping:
 *
 * $(UL
 *   $(LI $(LREF ed25519PkToX25519) converts a recipient's 32-byte Ed25519
 *     public key to its 32-byte X25519 public key;)
 *   $(LI $(LREF ed25519SkToX25519) converts a 64-byte libsodium Ed25519 secret
 *     key (the `seed ‖ public-key` form) to its 32-byte X25519 secret key.)
 * )
 *
 * Both are thin, backend-templated wrappers (per SPEC §4.1): they default to
 * $(REF DefaultBackend, sparkles,crypto,backend) and are constrained on
 * $(REF hasEd25519ToX25519, sparkles,crypto,backend,traits), so a partial
 * backend lacking the conversion simply does not offer these functions. The
 * actual arithmetic lives in the backend (libsodium's
 * `crypto_sign_ed25519_*_to_curve25519`); this module only forwards.
 *
 * Like every libsodium-backed primitive, these wrappers are `@safe nothrow
 * @nogc` but $(B not) `pure`.
 *
 * See `docs/specs/age/SPEC.md` §6 (primitives) for the normative description.
 *
 * Copyright: © 2026, Petar Kirov
 * License: $(HTTP boost.org/LICENSE_1_0.txt, Boost License 1.0)
 * Authors: Petar Kirov
 */
module sparkles.crypto.ed25519;

import sparkles.crypto.backend : DefaultBackend, hasEd25519ToX25519, isCryptoBackend;

@safe nothrow @nogc:

/**
 * Convert an Ed25519 public key to its X25519 (Montgomery) public key.
 *
 * Used to derive the X25519 public key of an `ssh-ed25519` recipient.
 *
 * Params:
 *   edPk    = 32-byte Ed25519 public key
 *   curvePk = 32-byte output X25519 public key
 */
void ed25519PkToX25519(B = DefaultBackend)(in ubyte[32] edPk, ref ubyte[32] curvePk)
if (isCryptoBackend!B && hasEd25519ToX25519!B)
    => B.ed25519PkToX25519(edPk, curvePk);

/**
 * Convert an Ed25519 secret key to its X25519 (Montgomery) secret key.
 *
 * The libsodium Ed25519 secret key is the 64-byte `seed ‖ public-key` form, as
 * produced by `crypto_sign_ed25519_*_keypair`.
 *
 * Params:
 *   edSk    = 64-byte Ed25519 secret key
 *   curveSk = 32-byte output X25519 secret key
 */
void ed25519SkToX25519(B = DefaultBackend)(in ubyte[64] edSk, ref ubyte[32] curveSk)
if (isCryptoBackend!B && hasEd25519ToX25519!B)
    => B.ed25519SkToX25519(edSk, curveSk);

// ─────────────────────────────────────────────────────────────────────────
// Tests
//
// The fixed Ed25519 key pair below was generated by libsodium from a
// deterministic 32-byte seed (every byte 0x42) via
// `crypto_sign_ed25519_seed_keypair`; its X25519 conversions were then
// computed once with libsodium and pinned here as a known-answer vector. The
// `edSk` is the 64-byte `seed ‖ public-key` form, hence its first 32 bytes are
// the seed (0x42…) and its last 32 bytes equal `edPk`.
// ─────────────────────────────────────────────────────────────────────────

version (unittest)
{
    import sparkles.crypto.encoding.hex : decodeHex;

    /// Decode a compile-time-known hex string into a fixed `ubyte[N]`,
    /// asserting it decodes cleanly. `N` is the expected byte length.
    private ubyte[N] fromHex(size_t N)(scope const(char)[] s) @safe nothrow @nogc
    in (s.length == N * 2, "fromHex: hex length does not match N")
    {
        ubyte[N] out_ = void;
        auto r = decodeHex(s, out_[]);
        assert(r.hasValue, "fromHex: invalid hex literal");
        assert(r.value.length == N, "fromHex: decoded length mismatch");
        return out_;
    }
}

/// `ed25519PkToX25519` matches the precomputed X25519 public key for a fixed
/// Ed25519 public key (libsodium known-answer vector).
@("crypto.ed25519.ed25519PkToX25519.knownAnswer")
@safe nothrow @nogc
unittest
{
    const edPk = fromHex!32(
        "2152f8d19b791d24453242e15f2eab6cb7cffa7b6a5ed30097960e069881db12");
    const expectedCurvePk = fromHex!32(
        "cc4f2cdb695dd766f34118eb67b98652fed1d8bc49c330b119bbfa8a64989378");

    ubyte[32] curvePk = void;
    ed25519PkToX25519(edPk, curvePk);
    assert(curvePk == expectedCurvePk);
}

/// `ed25519SkToX25519` matches the precomputed X25519 secret key for the fixed
/// 64-byte Ed25519 secret key (libsodium known-answer vector).
@("crypto.ed25519.ed25519SkToX25519.knownAnswer")
@safe nothrow @nogc
unittest
{
    // 64-byte secret key: 32-byte seed (0x42…) ‖ 32-byte public key.
    const edSk = fromHex!64(
        "4242424242424242424242424242424242424242424242424242424242424242"
        ~ "2152f8d19b791d24453242e15f2eab6cb7cffa7b6a5ed30097960e069881db12");
    const expectedCurveSk = fromHex!32(
        "90e7595fc89e52fdfddce9c6a43d74dbf6047025ee0462d2d172e8b6a2841d6e");

    ubyte[32] curveSk = void;
    ed25519SkToX25519(edSk, curveSk);
    assert(curveSk == expectedCurveSk);
}

/// The two conversions are self-consistent: converting both halves of the same
/// Ed25519 key pair yields an X25519 key pair, i.e. the base-point multiple of
/// the converted secret key equals the converted public key. This holds purely
/// through the public, backend-templated surface (no keypair generator needed).
@("crypto.ed25519.conversion.selfConsistent")
@safe nothrow @nogc
unittest
{
    import sparkles.crypto.backend : DefaultBackend;

    const edPk = fromHex!32(
        "2152f8d19b791d24453242e15f2eab6cb7cffa7b6a5ed30097960e069881db12");
    const edSk = fromHex!64(
        "4242424242424242424242424242424242424242424242424242424242424242"
        ~ "2152f8d19b791d24453242e15f2eab6cb7cffa7b6a5ed30097960e069881db12");

    ubyte[32] curvePk = void, curveSk = void;
    ed25519PkToX25519(edPk, curvePk);
    ed25519SkToX25519(edSk, curveSk);

    // The X25519 public key derived from the converted secret key must match
    // the directly converted public key.
    ubyte[32] derivedPk = void;
    DefaultBackend.x25519Base(curveSk, derivedPk);
    assert(derivedPk == curvePk);
}
