/++
Golden files: compare against one, or bless it.

Three packages had grown their own copy of the same twenty lines — `dmd-fmt`'s
markdown case runner, `source-view`'s markdown grid fixtures, and hue's DSV
grids — and they had drifted apart in ways that matter:

$(LIST
    $(ITEM Two accepted any non-empty `SPARKLES_UPDATE_GOLDENS`; one required
        exactly `1`. So `SPARKLES_UPDATE_GOLDENS=0` blessed two of the three
        suites.)
    $(ITEM One treated a $(I missing) golden as a reason to write it and pass.
        A fixture that never got committed then goes green in CI forever,
        having asserted nothing.)
)

This module is the one copy. Its policies are stated rather than inherited:

$(LIST
    $(ITEM $(B Only a plain mismatch is blessable.) `dmd-fmt` verifies each
        formatting besides comparing it, and a run where the verifier objected
        must not be recorded as the new truth — the whole point of a golden is
        that a human looked at the diff, and a blessed wrong answer is worse
        than a red test. $(LREF blessGolden) exists for the caller that has
        checked something first; $(LREF checkGolden) is the compare-only form.)
    $(ITEM $(B A missing golden is a failure.) Not silently created: a test
        that writes its own expectation on first run asserts nothing on that
        run, and in CI a fixture left out of a commit would pass. The message
        says how to create it.)
    $(ITEM $(B The regeneration command travels with the failure.) Each suite
        is regenerated by a different `dub test` invocation, so the message has
        to carry it — a golden failure is read by someone who did not write the
        suite.)
)
+/
module sparkles.test_utils.goldens;

import std.process : environment;

/// The variable that turns a comparison into a blessing.
enum goldenBlessEnvVar = "SPARKLES_UPDATE_GOLDENS";

/**
Is this run allowed to rewrite goldens?

`SPARKLES_UPDATE_GOLDENS=1`, and nothing else. `dmd-fmt` already required
exactly that while the other two accepted any non-empty value, which made
`SPARKLES_UPDATE_GOLDENS=0` — the spelling anyone reaches for to turn a
variable $(I off) — bless two suites out of three.
*/
bool blessingGoldens() @safe
{
    try
        return environment.get(goldenBlessEnvVar, "") == "1";
    catch (Exception)
        return false;
}

/**
Compares `actual` against the golden file at `path`, or rewrites it.

Params:
    actual = what the code under test produced
    path = the golden file
    regenerateWith = the exact command that blesses this suite, quoted back to
        whoever reads the failure. They will usually not be the person who
        wrote the test.
    file = the caller's file, for the assertion's location
    line = ditto

Throws: `AssertError` when the file is missing or its contents differ.
*/
void checkGolden(const(char)[] actual, string path, string regenerateWith,
    string file = __FILE__, size_t line = __LINE__) @safe
{
    import std.file : exists, readText;

    if (blessingGoldens())
    {
        blessGolden(actual, path);
        return;
    }

    if (!path.exists)
        fail(path ~ " does not exist yet — create it with `"
            ~ regenerateWith ~ "`, then review and commit it", file, line);

    const expected = readText(path);
    if (actual == expected)
        return;

    fail(path ~ " differs from what the code produces now"
        ~ describeDivergence(expected, actual)
        ~ ". If the change is intended, regenerate with `"
        ~ regenerateWith ~ "` and read the diff before committing it",
        file, line);
}

/**
Writes `actual` to `path` unconditionally — a blessing the caller has decided
on.

Separate from $(LREF checkGolden) so a suite that verifies its output by other
means can refuse to bless a run those checks rejected. `dmd-fmt` is the case:
it compares, then proves token equality and convergence, and a golden recorded
from a run the verifier objected to would enshrine a formatting that loses
code.
*/
void blessGolden(const(char)[] actual, string path) @safe
{
    import std.file : mkdirRecurse, write;
    import std.path : dirName;

    mkdirRecurse(path.dirName);
    write(path, actual);
}

/**
Where two texts first part company, as a phrase for a failure message.

A whole-file diff is what `diffWithTool` is for and costs a subprocess; this is
the one fact that makes a golden failure navigable — which line to look at —
and costs nothing.
*/
string describeDivergence(const(char)[] expected, const(char)[] actual) @safe
{
    import std.algorithm : splitter;
    import std.array : array;
    import std.conv : to;

    auto e = expected.splitter('\n').array;
    auto a = actual.splitter('\n').array;

    string note;
    if (e.length != a.length)
        note = a.length > e.length
            ? ", " ~ (a.length - e.length).to!string ~ " lines longer"
            : ", " ~ (e.length - a.length).to!string ~ " lines shorter";

    const shared_ = e.length < a.length ? e.length : a.length;
    foreach (i; 0 .. shared_)
        if (e[i] != a[i])
            return (" (first at line " ~ (i + 1).to!string ~ ": expected `"
                ~ elide(e[i]) ~ "`, got `" ~ elide(a[i]) ~ "`" ~ note ~ ")").idup;

    // A common prefix and a different length: nothing changed, something was
    // added or removed at the end. Which way round is the whole finding.
    if (note.length != 0)
        return " (identical through line " ~ shared_.to!string ~ note ~ ")";
    return "";
}

private size_t count(const(char)[] s, char c) @safe pure nothrow @nogc
{
    size_t n;
    foreach (ch; s)
        if (ch == c)
            ++n;
    return n;
}

private const(char)[] elide(const(char)[] s, size_t max = 60) @safe pure nothrow
    => s.length <= max ? s : s[0 .. max] ~ "…";

private void fail(string message, string file, size_t line) @safe
{
    import core.exception : AssertError;

    throw new AssertError(message, file, line);
}

/**
A cell grid rendered as plain text: one line per row, trailing blanks trimmed.

Every golden that photographs a laid-out widget tree wants exactly this, and
`source-view` and hue had byte-identical copies of it. A template rather than a
function over `CellGrid`, so this package keeps its "depends on nothing"
property — `sparkles:ui` is not in its closure and must not be.

$(B Colour is deliberately absent.) A grid golden is the layout oracle: what is
where, at what width. Folding style into it would make a theme change rewrite
every fixture and bury the one line that moved.
*/
string gridText(Grid)(in Grid grid) @safe
{
    import std.utf : encode;

    string text;
    foreach (y; 0 .. grid.height)
    {
        size_t lineEnd = text.length;
        foreach (x; 0 .. grid.width)
        {
            char[4] buf;
            const n = encode(buf, grid.cells[y * grid.width + x].glyph);
            text ~= buf[0 .. n];
            if (grid.cells[y * grid.width + x].glyph != ' ')
                lineEnd = text.length;
        }
        text = text[0 .. lineEnd];
        text ~= '\n';
    }
    return text;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

@("test_utils.goldens.blessOnlyOnExactlyOne")
@safe
unittest
{
    const had = environment.get(goldenBlessEnvVar, null);
    scope (exit)
    {
        if (had is null)
            environment.remove(goldenBlessEnvVar);
        else
            environment[goldenBlessEnvVar] = had;
    }

    environment.remove(goldenBlessEnvVar);
    assert(!blessingGoldens);

    environment[goldenBlessEnvVar] = "1";
    assert(blessingGoldens);

    // The spelling anyone reaches for to turn a variable off. Two of the three
    // suites this replaces blessed on it.
    environment[goldenBlessEnvVar] = "0";
    assert(!blessingGoldens);
    environment[goldenBlessEnvVar] = "";
    assert(!blessingGoldens);
    environment[goldenBlessEnvVar] = "yes";
    assert(!blessingGoldens);
}

@("test_utils.goldens.aMissingGoldenIsAFailureNotABlessing")
@system
unittest
{
    import core.exception : AssertError;
    import sparkles.test_utils.tmpfs : TmpFS;
    import std.algorithm : canFind;
    import std.file : exists;
    import std.path : buildPath;

    auto tmp = TmpFS.create();
    tmp.ensureDir();
    const path = tmp.dir.buildPath("absent.txt");

    bool threw;
    try
        checkGolden("something", path, "dub test :thing -- -i golden");
    catch (AssertError e)
    {
        threw = true;
        // The command has to be in the message: whoever reads this did not
        // write the suite and cannot guess how it is regenerated.
        assert(e.msg.canFind("dub test :thing -- -i golden"), e.msg);
    }
    assert(threw, "a golden that does not exist must not silently be created");
    assert(!path.exists);
}

@("test_utils.goldens.matchPassesMismatchNamesTheLine")
@system
unittest
{
    import core.exception : AssertError;
    import sparkles.test_utils.tmpfs : TmpFS;
    import std.algorithm : canFind;
    import std.path : buildPath;

    auto tmp = TmpFS.create();
    const path = tmp.writeFile("alpha\nbeta\ngamma\n");

    checkGolden("alpha\nbeta\ngamma\n", path, "regen");

    bool threw;
    try
        checkGolden("alpha\nBETA\ngamma\n", path, "regen");
    catch (AssertError e)
    {
        threw = true;
        assert(e.msg.canFind("line 2"), e.msg);
        assert(e.msg.canFind("regen"), e.msg);
    }
    assert(threw);
}

@("test_utils.goldens.divergenceDistinguishesGrowthFromLoss")
@safe
unittest
{
    import std.algorithm : canFind;

    // A shared prefix and a different length is the common case for a grid
    // golden: a row appeared, or one went missing. Which way round is the
    // whole finding.
    assert(describeDivergence("a\nb\n", "a\nb\nc\n").canFind("1 lines longer"));
    assert(describeDivergence("a\nb\nc\n", "a\nb\n").canFind("1 lines shorter"));
    assert(describeDivergence("a\nb\n", "a\nb\n") == "");

    // A pure append leaves no differing line to point at, so the message says
    // how far the two agreed instead of reporting nothing.
    const appended = describeDivergence("a\nb", "a\nb\nc");
    assert(appended.canFind("identical through line 2"), appended);
    assert(appended.canFind("1 lines longer"), appended);

    // A long line is elided rather than pasted whole into the message.
    const wide = describeDivergence(
        "x", "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy");
    assert(wide.canFind("…"), wide);
}

@("test_utils.goldens.blessingRewritesAndCreatesTheDirectory")
@system
unittest
{
    import sparkles.test_utils.tmpfs : TmpFS;
    import std.file : readText;
    import std.path : buildPath;

    auto tmp = TmpFS.create();
    tmp.ensureDir();
    const path = tmp.dir.buildPath("nested", "deeper", "g.txt");

    blessGolden("first\n", path);
    assert(readText(path) == "first\n");

    blessGolden("second\n", path);
    assert(readText(path) == "second\n");
}

@("test_utils.goldens.gridTextTrimsTrailingBlanks")
@safe
unittest
{
    // The stand-in is the shape every caller's grid has: `width`, `height`,
    // and `cells[y * width + x].glyph`. Nothing here knows about `sparkles:ui`.
    static struct Cell { dchar glyph; }
    static struct Grid
    {
        size_t width, height;
        Cell[] cells;
    }

    auto g = Grid(4, 2, [
        Cell('a'), Cell('b'), Cell(' '), Cell(' '),
        Cell(' '), Cell('c'), Cell(' '), Cell(' '),
    ]);
    assert(gridText(g) == "ab\n c\n");

    // A wholly blank row is an empty line, not four spaces: a golden full of
    // invisible trailing whitespace is one nobody can review.
    auto blank = Grid(2, 1, [Cell(' '), Cell(' ')]);
    assert(gridText(blank) == "\n");
}
