/// Public import surface for the `libghostty-vt` bindings.
///
/// The raw ImportC declarations live in `sparkles.ghostty.c` (generated by
/// compiling `c.c`, which `#include`s `<ghostty/vt.h>`). Import this package to
/// pull them in as `import sparkles.ghostty;`.
module sparkles.ghostty;

public import sparkles.ghostty.c;
