/**
`terminal config show` and `terminal config write` (`TCF5`), and the write-back
the settings page uses: the terminal's bindings of `sparkles.wired.config_file`
to `TerminalConfig`, its origins and its `@Description` texts. All three render
from the same resolved value, so what the app reports, the file a user starts
from and what it saves cannot disagree.

NOTE: no module-level `@safe:` — the encode/decode walks infer `@system`.
*/
module settings_io;

import expected : Expected;

import sparkles.metadata : Description;
import sparkles.wired.config_file : renderConfigShowWith = renderConfigShow,
    renderStarterSections, saveSparseConfig, SaveRefusal;
import sparkles.wired.overlay : Sparse;

import settings : TerminalConfig;
import settings_load : LoadedConfig, Origin;

private string originText(Origin o) @safe pure nothrow => o.text;
private bool isDefaultOrigin(Origin o) @safe pure nothrow @nogc => o.isDefault;

/**
Writes the load warnings, then every effective setting prefixed with the
layer that supplied it (`default`, `termux:<file>`, `file:<path>`,
`cli:<flag>`). `changedOnly` keeps the settings not at their defaults.
*/
void renderConfigShow(Writer)(ref Writer w, in LoadedConfig lc, bool changedOnly = false)
{
    foreach (warning; lc.warnings)
    {
        w ~= warning;
        w ~= '\n';
    }
    renderConfigShowWith!(originText, isDefaultOrigin)(w, lc.effective, lc.origins,
        changedOnly);
}

/**
Emits the commented starting file: every setting commented out with its
description and compiled default. Stripped of comments it is the empty
layer, so writing it changes nothing until the user uncomments a line.
*/
void renderStarterConfig(Writer)(ref Writer w)
{
    w ~= "{\n";
    w ~= "  // sparkles:terminal configuration — generated by `terminal config write`.\n";
    w ~= "  // Every setting is optional: an absent one inherits from the layer below\n";
    w ~= "  // (the compiled defaults, then ~/.termux on Android). Comments and\n";
    w ~= "  // trailing commas are accepted.\n";
    renderStarterSections!Description(w, TerminalConfig.init);
    w ~= "}\n";
}

/// Persists `existing ∪ deltas` as the config file — only what the user
/// changed, never a value a lower or higher layer supplied (`TSP3`).
Expected!(void, SaveRefusal) saveConfig(string path, Sparse!TerminalConfig existing,
    Sparse!TerminalConfig deltas, bool force = false)
    => saveSparseConfig!TerminalConfig(path, existing, deltas, "the terminal", force);

// ─────────────────────────────────────────────────────────────────────────────
// Tests.
// ─────────────────────────────────────────────────────────────────────────────

@("settings_io.renderConfigShow.namesEveryLayer")
@system unittest
{
    import std.algorithm.searching : canFind;
    import std.array : appender;
    import std.path : buildPath;
    import std.string : splitLines;

    import sparkles.test_utils.tmpfs : TmpFS;

    import settings_load : loadTerminalConfig;

    auto fixture = TmpFS.create();
    fixture.writeFileAt(".termux/termux.properties", "extra-keys = [['ESC']]\n");
    const file = fixture.writeFileAt("config.json", `{"paste":{"confirm":"never"}}`);
    auto lc = loadTerminalConfig(file, buildPath(fixture.dir, ".termux"));
    Sparse!TerminalConfig cli;
    cli.appearance.font.size = 9;
    lc.applyCli(cli, "--font-size");

    auto w = appender!string;
    renderConfigShow(w, lc);
    const lines = w[].splitLines;
    bool has(string origin, string setting)
        => lines.canFind!(l => l.length > origin.length && l[0 .. origin.length] == origin
            && l.canFind(" " ~ setting));
    assert(has("termux:termux.properties", "extraKeys.layout=[['ESC']]"), w[]);
    assert(has("file:" ~ file, "paste.confirm=never"), w[]);
    assert(has("cli:--font-size", "appearance.font.size=9"), w[]);
    assert(has("default", "behaviour.onExit=promptOnFailure"), w[]);

    // Every leaf of the schema appears once (`TCF1`): the listing and the
    // aggregate cannot drift apart.
    assert(lines.length == leafCount!TerminalConfig, w[]);

    auto changed = appender!string;
    renderConfigShow(changed, lc, changedOnly: true);
    assert(changed[].splitLines.length == 3, changed[]);
}

@("settings_io.renderStarterConfig.isTheEmptyLayerAndDocumented")
@system unittest
{
    import std.algorithm.searching : canFind, count;
    import std.array : appender;

    import sparkles.wired.json : fromJSON;
    import sparkles.wired.json.jsonc : stripJsonc;

    auto w = appender!string;
    renderStarterConfig(w);
    auto text = w[].dup;
    stripJsonc(text);
    auto r = fromJSON!(Sparse!TerminalConfig)(text);
    assert(!r.hasError, r.error.toString);
    assert(r.value == Sparse!TerminalConfig.init);

    assert(w[].canFind(`// "onExit": "promptOnFailure",`), w[]);
    assert(w[].canFind(`// "visible": "auto",`), w[]);
    assert(w[].canFind(`// What a pane does when its program exits.`));
    // Every leaf is in the starter file too (`TCF1`).
    assert(w[].count(`// "`) == leafCount!TerminalConfig);
}

version (unittest)
/// The schema's leaves, counted by reflection: the third enumeration the
/// `TCF1` test compares the listing and the starter file against.
private template leafCount(T)
{
    import std.traits : FieldNameTuple, hasUDA;

    import sparkles.wired.overlay : WireSection;

    enum leafCount = () {
        size_t n;
        static foreach (i, _; FieldNameTuple!T)
        {
            static if (hasUDA!(typeof(T.tupleof[i]), WireSection))
                n += leafCount!(typeof(T.tupleof[i]));
            else
                n++;
        }
        return n;
    }();
}
