/**
The pure half of the APK asset bundle: manifest-entry containment, the
freshness check, and the `KEY=VALUE` env-file format. Free of version gates so
`dub test :android` exercises them on any host; the `AAssetManager` half lives
in $(MREF sparkles,android,assets).

A bundle is what the nix build assembles into the APK's `assets/`: the files
themselves, `asset-manifest.txt` (one relative path per line — `AAssetDir`
cannot enumerate subdirectories, so the manifest IS the directory listing),
and `bundle-hash`, which keys the idempotent first-run extraction.
*/
module sparkles.android.bundle;

import std.string : indexOf, splitLines, startsWith, strip;

/**
`true` when `rel` is a manifest entry safe to join onto the data dir: a
non-empty relative path with no `..` component.

The manifest ships inside the APK and is generated by the nix build, so this
is not a trust boundary — it is a containment invariant kept local instead of
resting on a property of a different file in a different language. Two things
it catches: D's `buildPath` $(I discards) everything before a rooted segment
(`buildPath("/data/x", "/etc/y") == "/etc/y"`), and the generator is
newline-delimited, so a tracked filename containing a newline would split into
two garbage entries.
*/
bool isSafeAssetRel(const(char)[] rel) @safe pure
{
    import std.path : isRooted, pathSplitter;

    if (rel.length == 0 || rel.isRooted)
        return false;
    foreach (part; rel.pathSplitter)
        if (part == "..")
            return false;
    return true;
}

///
@("android.bundle.isSafeAssetRel")
@safe pure unittest
{
    assert(isSafeAssetRel("fonts/Maple.ttf"));
    assert(isSafeAssetRel("grammars/d/queries/highlights.scm"));
    assert(!isSafeAssetRel(""));
    assert(!isSafeAssetRel("/data/local/tmp/x")); // buildPath would honour this
    assert(!isSafeAssetRel("../../etc/passwd"));
    assert(!isSafeAssetRel("fonts/../../escape"));
    // A lone dot is redundant but harmless, and stays allowed.
    assert(isSafeAssetRel("./fonts/Maple.ttf"));
}

/// `true` when the on-device marker matches the APK's bundle hash
/// (whitespace-insensitively) — the extracted assets are current and
/// extraction can be skipped. Empty hashes never match.
bool assetsUpToDate(const(char)[] markerText, const(char)[] bundleHash) @safe pure
{
    const m = markerText.strip;
    return m.length != 0 && m == bundleHash.strip;
}

///
@("android.bundle.assetsUpToDate")
@safe pure unittest
{
    assert(assetsUpToDate("abc123\n", "abc123"));
    assert(!assetsUpToDate("abc123", "def456"));
    assert(!assetsUpToDate("", ""));
    assert(!assetsUpToDate("\n", "\n"));
}

/// One parsed `KEY=VALUE` line of an env file.
struct EnvPair
{
    string key, value;
}

/**
Parse `KEY=VALUE` lines — the on-device stand-in for shell environment
variables (an activity has no shell; the file is pushed via
`adb shell run-as <package>`). `#` comments and blank lines are skipped, the
first `=` splits, key and value are trimmed. Pairs return in file order.
*/
EnvPair[] parseEnvFile(const(char)[] text) @safe pure
{
    EnvPair[] result;
    foreach (line; text.splitLines)
    {
        const s = line.strip;
        if (s.length == 0 || s.startsWith("#"))
            continue;
        const eq = s.indexOf('=');
        if (eq <= 0)
            continue;
        result ~= EnvPair(s[0 .. eq].strip.idup, s[eq + 1 .. $].strip.idup);
    }
    return result;
}

///
@("android.bundle.parseEnvFile")
@safe pure unittest
{
    const pairs = parseEnvFile(
        "# golden capture\nHUE_GUI_SCREENSHOT=shot.png\n\n" ~
        "  HUE_GUI_FONTSIZE = 18 \n=nokey\nnovalue\nHUE_GUI_TOP=3\n");
    assert(pairs.length == 3);
    assert(pairs[0] == EnvPair("HUE_GUI_SCREENSHOT", "shot.png"));
    assert(pairs[1] == EnvPair("HUE_GUI_FONTSIZE", "18"));
    assert(pairs[2] == EnvPair("HUE_GUI_TOP", "3"));
    assert(parseEnvFile("").length == 0);
}
