// Generated by libs/base/tools/gen_unicode_tables.d — DO NOT EDIT.
//
// Unicode 17.0.0 East Asian Width (UAX #11) and emoji variation
// selector bases (UTS #51) — the properties std.uni does not ship.
// Pinned to match the toolchain's std.uni grapheme tables. Regenerate
// by running ./libs/base/tools/gen_unicode_tables.d.
module sparkles.base.text.unicode_tables;

bool isEastAsianWide(dchar ch) @safe pure nothrow @nogc
{
    if (ch < 94208)
    {
        if (ch < 10071)
        {
            if (ch < 9917)
            {
                if (ch < 9748)
                {
                    if (ch < 9193)
                    {
                        if (ch < 8986)
                        {
                            if (ch < 4352) return false;
                            if (ch < 4448) return true;
                            return false;
                        }
                        else if (ch < 8988) return true;
                        else
                        {
                            if (ch == 9001 || ch == 9002) return true;
                            return false;
                        }
                    }
                    else if (ch < 9197) return true;
                    else
                    {
                        if (ch < 9203)
                        {
                            if (ch == 9200) return true;
                            return false;
                        }
                        else if (ch < 9204) return true;
                        else
                        {
                            if (ch == 9725 || ch == 9726) return true;
                            return false;
                        }
                    }
                }
                else if (ch < 9750) return true;
                else
                {
                    if (ch < 9866)
                    {
                        if (ch < 9800)
                        {
                            if (ch < 9776) return false;
                            if (ch < 9784) return true;
                            return false;
                        }
                        else if (ch < 9812) return true;
                        else
                        {
                            if (ch == 9855) return true;
                            return false;
                        }
                    }
                    else if (ch < 9872) return true;
                    else
                    {
                        if (ch < 9889)
                        {
                            if (ch == 9875) return true;
                            return false;
                        }
                        else if (ch < 9890) return true;
                        else
                        {
                            if (ch == 9898 || ch == 9899) return true;
                            return false;
                        }
                    }
                }
            }
            else if (ch < 9919) return true;
            else
            {
                if (ch < 9981)
                {
                    if (ch < 9962)
                    {
                        if (ch < 9934)
                        {
                            if (ch == 9924 || ch == 9925) return true;
                            return false;
                        }
                        else if (ch < 9935) return true;
                        else
                        {
                            if (ch == 9940) return true;
                            return false;
                        }
                    }
                    else if (ch < 9963) return true;
                    else
                    {
                        if (ch < 9973)
                        {
                            if (ch == 9970 || ch == 9971) return true;
                            return false;
                        }
                        else if (ch < 9974) return true;
                        else
                        {
                            if (ch == 9978) return true;
                            return false;
                        }
                    }
                }
                else if (ch < 9982) return true;
                else
                {
                    if (ch < 10060)
                    {
                        if (ch < 9994)
                        {
                            if (ch == 9989) return true;
                            return false;
                        }
                        else if (ch < 9996) return true;
                        else
                        {
                            if (ch == 10024) return true;
                            return false;
                        }
                    }
                    else if (ch < 10061) return true;
                    else
                    {
                        if (ch == 10062) return true;
                        if (ch < 10067) return false;
                        if (ch < 10070) return true;
                        return false;
                    }
                }
            }
        }
        else if (ch < 10072) return true;
        else
        {
            if (ch < 12783)
            {
                if (ch < 11931)
                {
                    if (ch < 11035)
                    {
                        if (ch < 10160)
                        {
                            if (ch < 10133) return false;
                            if (ch < 10136) return true;
                            return false;
                        }
                        else if (ch < 10161) return true;
                        else
                        {
                            if (ch == 10175) return true;
                            return false;
                        }
                    }
                    else if (ch < 11037) return true;
                    else
                    {
                        if (ch < 11093)
                        {
                            if (ch == 11088) return true;
                            return false;
                        }
                        else if (ch < 11094) return true;
                        else
                        {
                            if (ch < 11904) return false;
                            if (ch < 11930) return true;
                            return false;
                        }
                    }
                }
                else if (ch < 12020) return true;
                else
                {
                    if (ch < 12441)
                    {
                        if (ch < 12272)
                        {
                            if (ch < 12032) return false;
                            if (ch < 12246) return true;
                            return false;
                        }
                        else if (ch < 12351) return true;
                        else
                        {
                            if (ch < 12353) return false;
                            if (ch < 12439) return true;
                            return false;
                        }
                    }
                    else if (ch < 12544) return true;
                    else
                    {
                        if (ch < 12593)
                        {
                            if (ch < 12549) return false;
                            if (ch < 12592) return true;
                            return false;
                        }
                        else if (ch < 12687) return true;
                        else
                        {
                            if (ch < 12688) return false;
                            if (ch < 12774) return true;
                            return false;
                        }
                    }
                }
            }
            else if (ch < 12831) return true;
            else
            {
                if (ch < 65072)
                {
                    if (ch < 43360)
                    {
                        if (ch < 12880)
                        {
                            if (ch < 12832) return false;
                            if (ch < 12872) return true;
                            return false;
                        }
                        else if (ch < 42125) return true;
                        else
                        {
                            if (ch < 42128) return false;
                            if (ch < 42183) return true;
                            return false;
                        }
                    }
                    else if (ch < 43389) return true;
                    else
                    {
                        if (ch < 63744)
                        {
                            if (ch < 44032) return false;
                            if (ch < 55204) return true;
                            return false;
                        }
                        else if (ch < 64256) return true;
                        else
                        {
                            if (ch < 65040) return false;
                            if (ch < 65050) return true;
                            return false;
                        }
                    }
                }
                else if (ch < 65107) return true;
                else
                {
                    if (ch < 65504)
                    {
                        if (ch < 65128)
                        {
                            if (ch < 65108) return false;
                            if (ch < 65127) return true;
                            return false;
                        }
                        else if (ch < 65132) return true;
                        else
                        {
                            if (ch < 65281) return false;
                            if (ch < 65377) return true;
                            return false;
                        }
                    }
                    else if (ch < 65511) return true;
                    else
                    {
                        if (ch < 94176) return false;
                        if (ch < 94181) return true;
                        if (ch < 94192) return false;
                        if (ch < 94199) return true;
                        return false;
                    }
                }
            }
        }
    }
    else if (ch < 101590) return true;
    else
    {
        if (ch < 127992)
        {
            if (ch < 127374)
            {
                if (ch < 110928)
                {
                    if (ch < 110581)
                    {
                        if (ch < 101760)
                        {
                            if (ch < 101631) return false;
                            if (ch < 101663) return true;
                            return false;
                        }
                        else if (ch < 101875) return true;
                        else
                        {
                            if (ch < 110576) return false;
                            if (ch < 110580) return true;
                            return false;
                        }
                    }
                    else if (ch < 110588) return true;
                    else
                    {
                        if (ch < 110592)
                        {
                            if (ch == 110589 || ch == 110590) return true;
                            return false;
                        }
                        else if (ch < 110883) return true;
                        else
                        {
                            if (ch == 110898) return true;
                            return false;
                        }
                    }
                }
                else if (ch < 110931) return true;
                else
                {
                    if (ch < 119552)
                    {
                        if (ch < 110948)
                        {
                            if (ch == 110933) return true;
                            return false;
                        }
                        else if (ch < 110952) return true;
                        else
                        {
                            if (ch < 110960) return false;
                            if (ch < 111356) return true;
                            return false;
                        }
                    }
                    else if (ch < 119639) return true;
                    else
                    {
                        if (ch < 126980)
                        {
                            if (ch < 119648) return false;
                            if (ch < 119671) return true;
                            return false;
                        }
                        else if (ch < 126981) return true;
                        else
                        {
                            if (ch == 127183) return true;
                            return false;
                        }
                    }
                }
            }
            else if (ch < 127375) return true;
            else
            {
                if (ch < 127789)
                {
                    if (ch < 127552)
                    {
                        if (ch < 127488)
                        {
                            if (ch < 127377) return false;
                            if (ch < 127387) return true;
                            return false;
                        }
                        else if (ch < 127491) return true;
                        else
                        {
                            if (ch < 127504) return false;
                            if (ch < 127548) return true;
                            return false;
                        }
                    }
                    else if (ch < 127561) return true;
                    else
                    {
                        if (ch < 127584)
                        {
                            if (ch == 127568 || ch == 127569) return true;
                            return false;
                        }
                        else if (ch < 127590) return true;
                        else
                        {
                            if (ch < 127744) return false;
                            if (ch < 127777) return true;
                            return false;
                        }
                    }
                }
                else if (ch < 127798) return true;
                else
                {
                    if (ch < 127951)
                    {
                        if (ch < 127870)
                        {
                            if (ch < 127799) return false;
                            if (ch < 127869) return true;
                            return false;
                        }
                        else if (ch < 127892) return true;
                        else
                        {
                            if (ch < 127904) return false;
                            if (ch < 127947) return true;
                            return false;
                        }
                    }
                    else if (ch < 127956) return true;
                    else
                    {
                        if (ch < 127968) return false;
                        if (ch < 127985) return true;
                        if (ch == 127988) return true;
                        return false;
                    }
                }
            }
        }
        else if (ch < 128063) return true;
        else
        {
            if (ch < 128756)
            {
                if (ch < 128420)
                {
                    if (ch < 128331)
                    {
                        if (ch < 128066)
                        {
                            if (ch == 128064) return true;
                            return false;
                        }
                        else if (ch < 128253) return true;
                        else
                        {
                            if (ch < 128255) return false;
                            if (ch < 128318) return true;
                            return false;
                        }
                    }
                    else if (ch < 128335) return true;
                    else
                    {
                        if (ch < 128378)
                        {
                            if (ch < 128336) return false;
                            if (ch < 128360) return true;
                            return false;
                        }
                        else if (ch < 128379) return true;
                        else
                        {
                            if (ch == 128405 || ch == 128406) return true;
                            return false;
                        }
                    }
                }
                else if (ch < 128421) return true;
                else
                {
                    if (ch < 128720)
                    {
                        if (ch < 128640)
                        {
                            if (ch < 128507) return false;
                            if (ch < 128592) return true;
                            return false;
                        }
                        else if (ch < 128710) return true;
                        else
                        {
                            if (ch == 128716) return true;
                            return false;
                        }
                    }
                    else if (ch < 128723) return true;
                    else
                    {
                        if (ch < 128732)
                        {
                            if (ch < 128725) return false;
                            if (ch < 128729) return true;
                            return false;
                        }
                        else if (ch < 128736) return true;
                        else
                        {
                            if (ch == 128747 || ch == 128748) return true;
                            return false;
                        }
                    }
                }
            }
            else if (ch < 128765) return true;
            else
            {
                if (ch < 129678)
                {
                    if (ch < 129340)
                    {
                        if (ch < 129008)
                        {
                            if (ch < 128992) return false;
                            if (ch < 129004) return true;
                            return false;
                        }
                        else if (ch < 129009) return true;
                        else
                        {
                            if (ch < 129292) return false;
                            if (ch < 129339) return true;
                            return false;
                        }
                    }
                    else if (ch < 129350) return true;
                    else
                    {
                        if (ch < 129648)
                        {
                            if (ch < 129351) return false;
                            if (ch < 129536) return true;
                            return false;
                        }
                        else if (ch < 129661) return true;
                        else
                        {
                            if (ch < 129664) return false;
                            if (ch < 129675) return true;
                            return false;
                        }
                    }
                }
                else if (ch < 129735) return true;
                else
                {
                    if (ch < 129775)
                    {
                        if (ch < 129741)
                        {
                            if (ch == 129736) return true;
                            return false;
                        }
                        else if (ch < 129757) return true;
                        else
                        {
                            if (ch < 129759) return false;
                            if (ch < 129771) return true;
                            return false;
                        }
                    }
                    else if (ch < 129785) return true;
                    else
                    {
                        if (ch < 131072) return false;
                        if (ch < 196606) return true;
                        if (ch < 196608) return false;
                        if (ch < 262142) return true;
                        return false;
                    }
                }
            }
        }
    }
}

bool isEastAsianAmbiguous(dchar ch) @safe pure nothrow @nogc
{
    if (ch < 8592)
    {
        if (ch < 609)
        {
            if (ch < 275)
            {
                if (ch < 222)
                {
                    if (ch < 176)
                    {
                        if (ch < 167)
                        {
                            if (ch == 161) return true;
                            if (ch == 164) return true;
                            return false;
                        }
                        else if (ch < 169) return true;
                        else
                        {
                            if (ch == 170) return true;
                            if (ch == 173 || ch == 174) return true;
                            return false;
                        }
                    }
                    else if (ch < 181) return true;
                    else
                    {
                        if (ch < 198)
                        {
                            if (ch < 182) return false;
                            if (ch < 187) return true;
                            if (ch < 188) return false;
                            if (ch < 192) return true;
                            return false;
                        }
                        else if (ch < 199) return true;
                        else
                        {
                            if (ch == 208) return true;
                            if (ch == 215 || ch == 216) return true;
                            return false;
                        }
                    }
                }
                else if (ch < 226) return true;
                else
                {
                    if (ch < 247)
                    {
                        if (ch < 236)
                        {
                            if (ch == 230) return true;
                            if (ch < 232) return false;
                            if (ch < 235) return true;
                            return false;
                        }
                        else if (ch < 238) return true;
                        else
                        {
                            if (ch == 240) return true;
                            if (ch == 242 || ch == 243) return true;
                            return false;
                        }
                    }
                    else if (ch < 251) return true;
                    else
                    {
                        if (ch < 257)
                        {
                            if (ch == 252) return true;
                            if (ch == 254) return true;
                            return false;
                        }
                        else if (ch < 258) return true;
                        else
                        {
                            if (ch == 273) return true;
                            return false;
                        }
                    }
                }
            }
            else if (ch < 276) return true;
            else
            {
                if (ch < 358)
                {
                    if (ch < 319)
                    {
                        if (ch < 299)
                        {
                            if (ch == 283) return true;
                            if (ch == 294 || ch == 295) return true;
                            return false;
                        }
                        else if (ch < 300) return true;
                        else
                        {
                            if (ch < 305) return false;
                            if (ch < 308) return true;
                            if (ch == 312) return true;
                            return false;
                        }
                    }
                    else if (ch < 323) return true;
                    else
                    {
                        if (ch < 333)
                        {
                            if (ch == 324) return true;
                            if (ch < 328) return false;
                            if (ch < 332) return true;
                            return false;
                        }
                        else if (ch < 334) return true;
                        else
                        {
                            if (ch == 338 || ch == 339) return true;
                            return false;
                        }
                    }
                }
                else if (ch < 360) return true;
                else
                {
                    if (ch < 470)
                    {
                        if (ch < 464)
                        {
                            if (ch == 363) return true;
                            if (ch == 462) return true;
                            return false;
                        }
                        else if (ch < 465) return true;
                        else
                        {
                            if (ch == 466) return true;
                            if (ch == 468) return true;
                            return false;
                        }
                    }
                    else if (ch < 471) return true;
                    else
                    {
                        if (ch < 476)
                        {
                            if (ch == 472) return true;
                            if (ch == 474) return true;
                            return false;
                        }
                        else if (ch < 477) return true;
                        else
                        {
                            if (ch == 593) return true;
                            return false;
                        }
                    }
                }
            }
        }
        else if (ch < 610) return true;
        else
        {
            if (ch < 8240)
            {
                if (ch < 945)
                {
                    if (ch < 728)
                    {
                        if (ch < 713)
                        {
                            if (ch == 708) return true;
                            if (ch == 711) return true;
                            return false;
                        }
                        else if (ch < 716) return true;
                        else
                        {
                            if (ch == 717) return true;
                            if (ch == 720) return true;
                            return false;
                        }
                    }
                    else if (ch < 732) return true;
                    else
                    {
                        if (ch < 768)
                        {
                            if (ch == 733) return true;
                            if (ch == 735) return true;
                            return false;
                        }
                        else if (ch < 880) return true;
                        else
                        {
                            if (ch < 913) return false;
                            if (ch < 930) return true;
                            if (ch < 931) return false;
                            if (ch < 938) return true;
                            return false;
                        }
                    }
                }
                else if (ch < 962) return true;
                else
                {
                    if (ch < 8211)
                    {
                        if (ch < 1040)
                        {
                            if (ch < 963) return false;
                            if (ch < 970) return true;
                            if (ch == 1025) return true;
                            return false;
                        }
                        else if (ch < 1104) return true;
                        else
                        {
                            if (ch == 1105) return true;
                            if (ch == 8208) return true;
                            return false;
                        }
                    }
                    else if (ch < 8215) return true;
                    else
                    {
                        if (ch < 8224)
                        {
                            if (ch == 8216 || ch == 8217) return true;
                            if (ch == 8220 || ch == 8221) return true;
                            return false;
                        }
                        else if (ch < 8227) return true;
                        else
                        {
                            if (ch < 8228) return false;
                            if (ch < 8232) return true;
                            return false;
                        }
                    }
                }
            }
            else if (ch < 8241) return true;
            else
            {
                if (ch < 8457)
                {
                    if (ch < 8319)
                    {
                        if (ch < 8251)
                        {
                            if (ch == 8242 || ch == 8243) return true;
                            if (ch == 8245) return true;
                            return false;
                        }
                        else if (ch < 8252) return true;
                        else
                        {
                            if (ch == 8254) return true;
                            if (ch == 8308) return true;
                            return false;
                        }
                    }
                    else if (ch < 8320) return true;
                    else
                    {
                        if (ch < 8451)
                        {
                            if (ch < 8321) return false;
                            if (ch < 8325) return true;
                            if (ch == 8364) return true;
                            return false;
                        }
                        else if (ch < 8452) return true;
                        else
                        {
                            if (ch == 8453) return true;
                            return false;
                        }
                    }
                }
                else if (ch < 8458) return true;
                else
                {
                    if (ch < 8531)
                    {
                        if (ch < 8481)
                        {
                            if (ch == 8467) return true;
                            if (ch == 8470) return true;
                            return false;
                        }
                        else if (ch < 8483) return true;
                        else
                        {
                            if (ch == 8486) return true;
                            if (ch == 8491) return true;
                            return false;
                        }
                    }
                    else if (ch < 8533) return true;
                    else
                    {
                        if (ch < 8560)
                        {
                            if (ch < 8539) return false;
                            if (ch < 8543) return true;
                            if (ch < 8544) return false;
                            if (ch < 8556) return true;
                            return false;
                        }
                        else if (ch < 8570) return true;
                        else
                        {
                            if (ch == 8585) return true;
                            return false;
                        }
                    }
                }
            }
        }
    }
    else if (ch < 8602) return true;
    else
    {
        if (ch < 9670)
        {
            if (ch < 8800)
            {
                if (ch < 8730)
                {
                    if (ch < 8706)
                    {
                        if (ch < 8660)
                        {
                            if (ch == 8632 || ch == 8633) return true;
                            if (ch == 8658) return true;
                            return false;
                        }
                        else if (ch < 8661) return true;
                        else
                        {
                            if (ch == 8679) return true;
                            if (ch == 8704) return true;
                            return false;
                        }
                    }
                    else if (ch < 8708) return true;
                    else
                    {
                        if (ch < 8719)
                        {
                            if (ch == 8711 || ch == 8712) return true;
                            if (ch == 8715) return true;
                            return false;
                        }
                        else if (ch < 8720) return true;
                        else
                        {
                            if (ch == 8721) return true;
                            if (ch == 8725) return true;
                            return false;
                        }
                    }
                }
                else if (ch < 8731) return true;
                else
                {
                    if (ch < 8756)
                    {
                        if (ch < 8741)
                        {
                            if (ch < 8733) return false;
                            if (ch < 8737) return true;
                            if (ch == 8739) return true;
                            return false;
                        }
                        else if (ch < 8742) return true;
                        else
                        {
                            if (ch < 8743) return false;
                            if (ch < 8749) return true;
                            if (ch == 8750) return true;
                            return false;
                        }
                    }
                    else if (ch < 8760) return true;
                    else
                    {
                        if (ch < 8780)
                        {
                            if (ch == 8764 || ch == 8765) return true;
                            if (ch == 8776) return true;
                            return false;
                        }
                        else if (ch < 8781) return true;
                        else
                        {
                            if (ch == 8786) return true;
                            return false;
                        }
                    }
                }
            }
            else if (ch < 8802) return true;
            else
            {
                if (ch < 9312)
                {
                    if (ch < 8853)
                    {
                        if (ch < 8814)
                        {
                            if (ch < 8804) return false;
                            if (ch < 8808) return true;
                            if (ch == 8810 || ch == 8811) return true;
                            return false;
                        }
                        else if (ch < 8816) return true;
                        else
                        {
                            if (ch == 8834 || ch == 8835) return true;
                            if (ch == 8838 || ch == 8839) return true;
                            return false;
                        }
                    }
                    else if (ch < 8854) return true;
                    else
                    {
                        if (ch < 8895)
                        {
                            if (ch == 8857) return true;
                            if (ch == 8869) return true;
                            return false;
                        }
                        else if (ch < 8896) return true;
                        else
                        {
                            if (ch == 8978) return true;
                            return false;
                        }
                    }
                }
                else if (ch < 9450) return true;
                else
                {
                    if (ch < 9635)
                    {
                        if (ch < 9600)
                        {
                            if (ch < 9451) return false;
                            if (ch < 9548) return true;
                            if (ch < 9552) return false;
                            if (ch < 9588) return true;
                            return false;
                        }
                        else if (ch < 9616) return true;
                        else
                        {
                            if (ch < 9618) return false;
                            if (ch < 9622) return true;
                            if (ch == 9632 || ch == 9633) return true;
                            return false;
                        }
                    }
                    else if (ch < 9642) return true;
                    else
                    {
                        if (ch < 9660)
                        {
                            if (ch == 9650 || ch == 9651) return true;
                            if (ch == 9654 || ch == 9655) return true;
                            return false;
                        }
                        else if (ch < 9662) return true;
                        else
                        {
                            if (ch == 9664 || ch == 9665) return true;
                            return false;
                        }
                    }
                }
            }
        }
        else if (ch < 9673) return true;
        else
        {
            if (ch < 9960)
            {
                if (ch < 9824)
                {
                    if (ch < 9737)
                    {
                        if (ch < 9698)
                        {
                            if (ch == 9675) return true;
                            if (ch < 9678) return false;
                            if (ch < 9682) return true;
                            return false;
                        }
                        else if (ch < 9702) return true;
                        else
                        {
                            if (ch == 9711) return true;
                            if (ch == 9733 || ch == 9734) return true;
                            return false;
                        }
                    }
                    else if (ch < 9738) return true;
                    else
                    {
                        if (ch < 9758)
                        {
                            if (ch == 9742 || ch == 9743) return true;
                            if (ch == 9756) return true;
                            return false;
                        }
                        else if (ch < 9759) return true;
                        else
                        {
                            if (ch == 9792) return true;
                            if (ch == 9794) return true;
                            return false;
                        }
                    }
                }
                else if (ch < 9826) return true;
                else
                {
                    if (ch < 9919)
                    {
                        if (ch < 9836)
                        {
                            if (ch < 9827) return false;
                            if (ch < 9830) return true;
                            if (ch < 9831) return false;
                            if (ch < 9835) return true;
                            return false;
                        }
                        else if (ch < 9838) return true;
                        else
                        {
                            if (ch == 9839) return true;
                            if (ch == 9886 || ch == 9887) return true;
                            return false;
                        }
                    }
                    else if (ch < 9920) return true;
                    else
                    {
                        if (ch < 9941)
                        {
                            if (ch < 9926) return false;
                            if (ch < 9934) return true;
                            if (ch < 9935) return false;
                            if (ch < 9940) return true;
                            return false;
                        }
                        else if (ch < 9954) return true;
                        else
                        {
                            if (ch == 9955) return true;
                            return false;
                        }
                    }
                }
            }
            else if (ch < 9962) return true;
            else
            {
                if (ch < 65024)
                {
                    if (ch < 10045)
                    {
                        if (ch < 9974)
                        {
                            if (ch < 9963) return false;
                            if (ch < 9970) return true;
                            if (ch == 9972) return true;
                            return false;
                        }
                        else if (ch < 9978) return true;
                        else
                        {
                            if (ch == 9979 || ch == 9980) return true;
                            if (ch == 9982 || ch == 9983) return true;
                            return false;
                        }
                    }
                    else if (ch < 10046) return true;
                    else
                    {
                        if (ch < 12872)
                        {
                            if (ch < 10102) return false;
                            if (ch < 10112) return true;
                            if (ch < 11094) return false;
                            if (ch < 11098) return true;
                            return false;
                        }
                        else if (ch < 12880) return true;
                        else
                        {
                            if (ch < 57344) return false;
                            if (ch < 63744) return true;
                            return false;
                        }
                    }
                }
                else if (ch < 65040) return true;
                else
                {
                    if (ch < 127375)
                    {
                        if (ch < 127248)
                        {
                            if (ch == 65533) return true;
                            if (ch < 127232) return false;
                            if (ch < 127243) return true;
                            return false;
                        }
                        else if (ch < 127278) return true;
                        else
                        {
                            if (ch < 127280) return false;
                            if (ch < 127338) return true;
                            if (ch < 127344) return false;
                            if (ch < 127374) return true;
                            return false;
                        }
                    }
                    else if (ch < 127377) return true;
                    else
                    {
                        if (ch < 983040)
                        {
                            if (ch < 127387) return false;
                            if (ch < 127405) return true;
                            if (ch < 917760) return false;
                            if (ch < 918000) return true;
                            return false;
                        }
                        else if (ch < 1048574) return true;
                        else
                        {
                            if (ch < 1048576) return false;
                            if (ch < 1114110) return true;
                            return false;
                        }
                    }
                }
            }
        }
    }
}

bool isEmojiVsBase(dchar ch) @safe pure nothrow @nogc
{
    if (ch < 169)
    {
        if (ch < 42)
        {
            if (ch == 35) return true;
            return false;
        }
        else if (ch < 43) return true;
        else
        {
            if (ch < 48) return false;
            if (ch < 58) return true;
            return false;
        }
    }
    else if (ch < 170) return true;
    else
    {
        if (ch < 127490)
        {
            if (ch < 9904)
            {
                if (ch < 9757)
                {
                    if (ch < 9208)
                    {
                        if (ch < 8596)
                        {
                            if (ch < 8265)
                            {
                                if (ch == 174) return true;
                                if (ch == 8252) return true;
                                return false;
                            }
                            else if (ch < 8266) return true;
                            else
                            {
                                if (ch == 8482) return true;
                                if (ch == 8505) return true;
                                return false;
                            }
                        }
                        else if (ch < 8602) return true;
                        else
                        {
                            if (ch < 9000)
                            {
                                if (ch == 8617 || ch == 8618) return true;
                                if (ch == 8986 || ch == 8987) return true;
                                return false;
                            }
                            else if (ch < 9001) return true;
                            else
                            {
                                if (ch == 9167) return true;
                                if (ch < 9193) return false;
                                if (ch < 9204) return true;
                                return false;
                            }
                        }
                    }
                    else if (ch < 9211) return true;
                    else
                    {
                        if (ch < 9728)
                        {
                            if (ch < 9654)
                            {
                                if (ch == 9410) return true;
                                if (ch == 9642 || ch == 9643) return true;
                                return false;
                            }
                            else if (ch < 9655) return true;
                            else
                            {
                                if (ch == 9664) return true;
                                if (ch < 9723) return false;
                                if (ch < 9727) return true;
                                return false;
                            }
                        }
                        else if (ch < 9733) return true;
                        else
                        {
                            if (ch < 9748)
                            {
                                if (ch == 9742) return true;
                                if (ch == 9745) return true;
                                return false;
                            }
                            else if (ch < 9750) return true;
                            else
                            {
                                if (ch == 9752) return true;
                                return false;
                            }
                        }
                    }
                }
                else if (ch < 9758) return true;
                else
                {
                    if (ch < 9827)
                    {
                        if (ch < 9784)
                        {
                            if (ch < 9766)
                            {
                                if (ch == 9760) return true;
                                if (ch == 9762 || ch == 9763) return true;
                                return false;
                            }
                            else if (ch < 9767) return true;
                            else
                            {
                                if (ch == 9770) return true;
                                if (ch == 9774 || ch == 9775) return true;
                                return false;
                            }
                        }
                        else if (ch < 9787) return true;
                        else
                        {
                            if (ch < 9800)
                            {
                                if (ch == 9792) return true;
                                if (ch == 9794) return true;
                                return false;
                            }
                            else if (ch < 9812) return true;
                            else
                            {
                                if (ch == 9823 || ch == 9824) return true;
                                return false;
                            }
                        }
                    }
                    else if (ch < 9828) return true;
                    else
                    {
                        if (ch < 9881)
                        {
                            if (ch < 9851)
                            {
                                if (ch == 9829 || ch == 9830) return true;
                                if (ch == 9832) return true;
                                return false;
                            }
                            else if (ch < 9852) return true;
                            else
                            {
                                if (ch == 9854 || ch == 9855) return true;
                                if (ch < 9874) return false;
                                if (ch < 9880) return true;
                                return false;
                            }
                        }
                        else if (ch < 9882) return true;
                        else
                        {
                            if (ch < 9895)
                            {
                                if (ch == 9883 || ch == 9884) return true;
                                if (ch == 9888 || ch == 9889) return true;
                                return false;
                            }
                            else if (ch < 9896) return true;
                            else
                            {
                                if (ch == 9898 || ch == 9899) return true;
                                return false;
                            }
                        }
                    }
                }
            }
            else if (ch < 9906) return true;
            else
            {
                if (ch < 10055)
                {
                    if (ch < 9989)
                    {
                        if (ch < 9939)
                        {
                            if (ch < 9928)
                            {
                                if (ch == 9917 || ch == 9918) return true;
                                if (ch == 9924 || ch == 9925) return true;
                                return false;
                            }
                            else if (ch < 9929) return true;
                            else
                            {
                                if (ch == 9934 || ch == 9935) return true;
                                if (ch == 9937) return true;
                                return false;
                            }
                        }
                        else if (ch < 9941) return true;
                        else
                        {
                            if (ch < 9975)
                            {
                                if (ch == 9961 || ch == 9962) return true;
                                if (ch < 9968) return false;
                                if (ch < 9974) return true;
                                return false;
                            }
                            else if (ch < 9979) return true;
                            else
                            {
                                if (ch == 9981) return true;
                                if (ch == 9986) return true;
                                return false;
                            }
                        }
                    }
                    else if (ch < 9990) return true;
                    else
                    {
                        if (ch < 10013)
                        {
                            if (ch < 10002)
                            {
                                if (ch < 9992) return false;
                                if (ch < 9998) return true;
                                if (ch == 9999) return true;
                                return false;
                            }
                            else if (ch < 10003) return true;
                            else
                            {
                                if (ch == 10004) return true;
                                if (ch == 10006) return true;
                                return false;
                            }
                        }
                        else if (ch < 10014) return true;
                        else
                        {
                            if (ch < 10035)
                            {
                                if (ch == 10017) return true;
                                if (ch == 10024) return true;
                                return false;
                            }
                            else if (ch < 10037) return true;
                            else
                            {
                                if (ch == 10052) return true;
                                return false;
                            }
                        }
                    }
                }
                else if (ch < 10056) return true;
                else
                {
                    if (ch < 11013)
                    {
                        if (ch < 10133)
                        {
                            if (ch < 10067)
                            {
                                if (ch == 10060) return true;
                                if (ch == 10062) return true;
                                return false;
                            }
                            else if (ch < 10070) return true;
                            else
                            {
                                if (ch == 10071) return true;
                                if (ch == 10083 || ch == 10084) return true;
                                return false;
                            }
                        }
                        else if (ch < 10136) return true;
                        else
                        {
                            if (ch < 10175)
                            {
                                if (ch == 10145) return true;
                                if (ch == 10160) return true;
                                return false;
                            }
                            else if (ch < 10176) return true;
                            else
                            {
                                if (ch == 10548 || ch == 10549) return true;
                                return false;
                            }
                        }
                    }
                    else if (ch < 11016) return true;
                    else
                    {
                        if (ch < 12951)
                        {
                            if (ch < 11093)
                            {
                                if (ch == 11035 || ch == 11036) return true;
                                if (ch == 11088) return true;
                                return false;
                            }
                            else if (ch < 11094) return true;
                            else
                            {
                                if (ch == 12336) return true;
                                if (ch == 12349) return true;
                                return false;
                            }
                        }
                        else if (ch < 12952) return true;
                        else
                        {
                            if (ch < 127344)
                            {
                                if (ch == 12953) return true;
                                if (ch == 126980) return true;
                                return false;
                            }
                            else if (ch < 127346) return true;
                            else
                            {
                                if (ch == 127358 || ch == 127359) return true;
                                return false;
                            }
                        }
                    }
                }
            }
        }
        else if (ch < 127491) return true;
        else
        {
            if (ch < 128223)
            {
                if (ch < 127981)
                {
                    if (ch < 127891)
                    {
                        if (ch < 127772)
                        {
                            if (ch < 127543)
                            {
                                if (ch == 127514) return true;
                                if (ch == 127535) return true;
                                return false;
                            }
                            else if (ch < 127544) return true;
                            else
                            {
                                if (ch < 127757) return false;
                                if (ch < 127760) return true;
                                if (ch == 127765) return true;
                                return false;
                            }
                        }
                        else if (ch < 127773) return true;
                        else
                        {
                            if (ch < 127798)
                            {
                                if (ch == 127777) return true;
                                if (ch < 127780) return false;
                                if (ch < 127789) return true;
                                return false;
                            }
                            else if (ch < 127799) return true;
                            else
                            {
                                if (ch == 127864) return true;
                                if (ch == 127869) return true;
                                return false;
                            }
                        }
                    }
                    else if (ch < 127892) return true;
                    else
                    {
                        if (ch < 127938)
                        {
                            if (ch < 127902)
                            {
                                if (ch == 127894 || ch == 127895) return true;
                                if (ch < 127897) return false;
                                if (ch < 127900) return true;
                                return false;
                            }
                            else if (ch < 127904) return true;
                            else
                            {
                                if (ch == 127911) return true;
                                if (ch < 127916) return false;
                                if (ch < 127919) return true;
                                return false;
                            }
                        }
                        else if (ch < 127939) return true;
                        else
                        {
                            if (ch < 127946)
                            {
                                if (ch == 127940) return true;
                                if (ch == 127942) return true;
                                return false;
                            }
                            else if (ch < 127951) return true;
                            else
                            {
                                if (ch < 127956) return false;
                                if (ch < 127969) return true;
                                return false;
                            }
                        }
                    }
                }
                else if (ch < 127982) return true;
                else
                {
                    if (ch < 128077)
                    {
                        if (ch < 128031)
                        {
                            if (ch < 127991)
                            {
                                if (ch == 127987) return true;
                                if (ch == 127989) return true;
                                return false;
                            }
                            else if (ch < 127992) return true;
                            else
                            {
                                if (ch == 128008) return true;
                                if (ch == 128021) return true;
                                return false;
                            }
                        }
                        else if (ch < 128032) return true;
                        else
                        {
                            if (ch < 128065)
                            {
                                if (ch == 128038) return true;
                                if (ch == 128063) return true;
                                return false;
                            }
                            else if (ch < 128067) return true;
                            else
                            {
                                if (ch < 128070) return false;
                                if (ch < 128074) return true;
                                return false;
                            }
                        }
                    }
                    else if (ch < 128079) return true;
                    else
                    {
                        if (ch < 128179)
                        {
                            if (ch < 128125)
                            {
                                if (ch == 128083) return true;
                                if (ch == 128106) return true;
                                return false;
                            }
                            else if (ch < 128126) return true;
                            else
                            {
                                if (ch == 128163) return true;
                                if (ch == 128176) return true;
                                return false;
                            }
                        }
                        else if (ch < 128180) return true;
                        else
                        {
                            if (ch < 128203)
                            {
                                if (ch == 128187) return true;
                                if (ch == 128191) return true;
                                return false;
                            }
                            else if (ch < 128204) return true;
                            else
                            {
                                if (ch == 128218) return true;
                                return false;
                            }
                        }
                    }
                }
            }
            else if (ch < 128224) return true;
            else
            {
                if (ch < 128481)
                {
                    if (ch < 128371)
                    {
                        if (ch < 128264)
                        {
                            if (ch < 128247)
                            {
                                if (ch < 128228) return false;
                                if (ch < 128231) return true;
                                if (ch < 128234) return false;
                                if (ch < 128238) return true;
                                return false;
                            }
                            else if (ch < 128248) return true;
                            else
                            {
                                if (ch < 128249) return false;
                                if (ch < 128252) return true;
                                if (ch == 128253) return true;
                                return false;
                            }
                        }
                        else if (ch < 128265) return true;
                        else
                        {
                            if (ch < 128329)
                            {
                                if (ch == 128269) return true;
                                if (ch == 128274 || ch == 128275) return true;
                                return false;
                            }
                            else if (ch < 128331) return true;
                            else
                            {
                                if (ch < 128336) return false;
                                if (ch < 128360) return true;
                                if (ch == 128367 || ch == 128368) return true;
                                return false;
                            }
                        }
                    }
                    else if (ch < 128378) return true;
                    else
                    {
                        if (ch < 128433)
                        {
                            if (ch < 128400)
                            {
                                if (ch == 128391) return true;
                                if (ch < 128394) return false;
                                if (ch < 128398) return true;
                                return false;
                            }
                            else if (ch < 128401) return true;
                            else
                            {
                                if (ch == 128421) return true;
                                if (ch == 128424) return true;
                                return false;
                            }
                        }
                        else if (ch < 128435) return true;
                        else
                        {
                            if (ch < 128465)
                            {
                                if (ch == 128444) return true;
                                if (ch < 128450) return false;
                                if (ch < 128453) return true;
                                return false;
                            }
                            else if (ch < 128468) return true;
                            else
                            {
                                if (ch < 128476) return false;
                                if (ch < 128479) return true;
                                return false;
                            }
                        }
                    }
                }
                else if (ch < 128482) return true;
                else
                {
                    if (ch < 128664)
                    {
                        if (ch < 128528)
                        {
                            if (ch < 128495)
                            {
                                if (ch == 128483) return true;
                                if (ch == 128488) return true;
                                return false;
                            }
                            else if (ch < 128496) return true;
                            else
                            {
                                if (ch == 128499) return true;
                                if (ch == 128506) return true;
                                return false;
                            }
                        }
                        else if (ch < 128529) return true;
                        else
                        {
                            if (ch < 128657)
                            {
                                if (ch == 128647) return true;
                                if (ch == 128653) return true;
                                return false;
                            }
                            else if (ch < 128658) return true;
                            else
                            {
                                if (ch == 128660) return true;
                                return false;
                            }
                        }
                    }
                    else if (ch < 128665) return true;
                    else
                    {
                        if (ch < 128717)
                        {
                            if (ch < 128697)
                            {
                                if (ch == 128685) return true;
                                if (ch == 128690) return true;
                                return false;
                            }
                            else if (ch < 128699) return true;
                            else
                            {
                                if (ch == 128700) return true;
                                if (ch == 128715) return true;
                                return false;
                            }
                        }
                        else if (ch < 128720) return true;
                        else
                        {
                            if (ch < 128752)
                            {
                                if (ch < 128736) return false;
                                if (ch < 128742) return true;
                                if (ch == 128745) return true;
                                return false;
                            }
                            else if (ch < 128753) return true;
                            else
                            {
                                if (ch == 128755) return true;
                                return false;
                            }
                        }
                    }
                }
            }
        }
    }
}
