/**
Config-file I/O for hue, over `sparkles.wired`'s shared pieces: the JSONC read
path (`sparkles.wired.json.jsonc` — a starter file carries comments a user
keeps, so hue must read them back) and the layered-file renderers
(`sparkles.wired.config_file`).

What stays here is what is hue's: `renderConfigShow` (`CFG10`, every
effective setting with the origin that supplied it, prefixed by the load
warnings), `renderStarterConfig` (`CFG13`, the commented starting file under
hue's own header) and `saveUserConfig` (`CFG11`) — each a thin binding of the
shared renderer to `HueConfig`, `Origin` and `@Doc`, so the file a user starts
from and the state hue reports cannot disagree.

NOTE: no module-level `@safe:` — the wired decode this module fronts infers
`@system` for aggregates.
*/
module settings_io;

import expected : Expected;

import sparkles.wired.config_file : renderConfigShowWith = renderConfigShow,
    renderStarterSections, saveSparseConfig, sparseTextOf = sparseText;
public import sparkles.wired.config_file : SaveRefusal;
public import sparkles.wired.json.jsonc : readJsoncFile, stripJsonc;
import sparkles.wired.json : fromJSON;

import sparkles.ui.property_tree : Doc;

import settings : HueConfig;
import settings_load : LoadedConfig;
import settings_overlay : Origin, OriginKind, Sparse;

// ─────────────────────────────────────────────────────────────────────────────
// `hue config show` — the layering made observable (CFG10).
// ─────────────────────────────────────────────────────────────────────────────

/// One rendered line's origin column, `git config --show-origin` style.
/// (By value — returning the detail out of a scoped `in` view is a dip1000
/// error, and an `Origin` is two words.)
private string originText(Origin o) @safe pure nothrow
    => o.kind == OriginKind.default_ ? "default"
        : o.detail.length ? o.detail : "cli";

private bool isDefaultOrigin(Origin o) @safe pure nothrow @nogc
    => o.kind == OriginKind.default_;

/**
Writes the load warnings, then every effective setting — defaults included,
so the output is a complete picture — prefixed with the origin that supplied
it. `changedOnly` filters to non-default origins.
*/
void renderConfigShow(Writer)(ref Writer w, in LoadedConfig lc,
    bool changedOnly = false)
{
    foreach (warning; lc.warnings)
    {
        w ~= warning;
        w ~= '\n';
    }
    renderConfigShowWith!(originText, isDefaultOrigin)(w, lc.effective,
        lc.origins, changedOnly);
}

// ─────────────────────────────────────────────────────────────────────────────
// `hue config write` — the commented starting file (CFG13).
// ─────────────────────────────────────────────────────────────────────────────

/**
Emits the JSONC starter: every setting as a commented-out assignment carrying
its `@Doc` description and its compiled default. The file decodes as the
empty overlay until the user uncomments something.
*/
void renderStarterConfig(Writer)(ref Writer w)
{
    w ~= "{\n";
    w ~= "  // hue configuration — generated by `hue config write`.\n";
    w ~= "  // Every setting is optional: an absent setting inherits from the\n";
    w ~= "  // layer below (compiled defaults, unless a project .hue.json or a\n";
    w ~= "  // flag speaks). Comments and trailing commas are accepted.\n";
    renderStarterSections!Doc(w, HueConfig.init);
    w ~= "}\n";
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests.
// ─────────────────────────────────────────────────────────────────────────────

@("settings_io.readJsoncFile.roundTrip")
@system unittest
{
    import sparkles.test_utils.tmpfs : TmpFS;
    import std.file : write;

    import settings : HueConfig;
    import settings_overlay : Sparse;

    // `TmpFS.create()` names the directory after this unittest, which is what
    // keeps the parallel-running tests out of each other's way.
    auto fixture = TmpFS.create();
    const path = fixture.writeFileAt("config.json", "{\n" ~
        "  // the theme hue starts with\n" ~
        "  \"appearance\": { \"theme\": \"builtin-dark\", },\n" ~
        "}\n");

    auto r = readJsoncFile!(Sparse!HueConfig)(path);
    assert(!r.hasError, r.error.toString);
    assert(r.value.appearance.theme.get == "builtin-dark");
    assert(r.value.panes.viewer.tabWidth.isNull);

    // A malformed value is a located decode error: the `$`-path names the
    // setting, the file is recorded (decode errors are path-addressed;
    // line/column belong to parse-stage errors).
    write(path, "{\n" ~
        "  // comment\n" ~
        "  \"panes\": { \"viewer\": { \"tabWidth\": \"eight\" } }\n" ~
        "}\n");
    auto bad = readJsoncFile!(Sparse!HueConfig)(path);
    assert(bad.hasError);
    import std.algorithm.searching : canFind;
    assert(bad.error.path[].canFind("tabWidth"), bad.error.toString);
    assert(bad.error.filePath[] == path);

    // A syntax error (after stripping) keeps its true line in the file the
    // user is looking at — the strip preserved every offset.
    write(path, "{\n" ~
        "  /* two\n" ~
        "     lines */\n" ~
        "  \"panes\": nope\n" ~
        "}\n");
    auto syn = readJsoncFile!(Sparse!HueConfig)(path);
    assert(syn.hasError);
    assert(syn.error.line == 4, syn.error.toString);
}


// ─────────────────────────────────────────────────────────────────────────────
// Renderer tests.
// ─────────────────────────────────────────────────────────────────────────────

@("settings_io.renderConfigShow.originsAndFilter")
@system unittest
{
    import std.algorithm.searching : canFind;
    import std.array : appender;
    import std.string : splitLines;

    import settings_load : LoadedConfig;
    import settings_overlay : applyOverlay, Sparse;

    LoadedConfig lc;
    Sparse!HueConfig user;
    user.appearance.theme = "builtin-dark";
    user.panes.viewer.tabWidth = 8;
    applyOverlay(lc.effective, lc.origins, user,
        Origin(OriginKind.userFile, "file:/home/u/.config/hue/config.json"));
    lc.warnings ~= "config: something was ignored";

    auto full = appender!string;
    renderConfigShow(full, lc);
    const lines = full[].splitLines;

    // Warnings first, then every leaf — defaults included.
    assert(lines[0] == "config: something was ignored");
    assert(full[].canFind(
        "file:/home/u/.config/hue/config.json        appearance.theme=builtin-dark"),
        full[]);
    assert(full[].canFind("default"), full[]);
    assert(full[].canFind("panes.viewer.tabWidth=8"));
    assert(full[].canFind("appearance.fonts.size=18"));
    assert(full[].canFind("behaviour.tableCopy=detect"));

    // --changed keeps exactly the non-default origins.
    auto changed = appender!string;
    renderConfigShow(changed, lc, changedOnly: true);
    const clines = changed[].splitLines;
    assert(clines.length == 3, changed[]); // warning + two set fields
    assert(!changed[].canFind("fonts.size"));
}

@("settings_io.renderStarterConfig.decodesEmptyAndDocumented")
@system unittest
{
    import std.algorithm.searching : canFind;
    import std.array : appender;

    import settings_overlay : Sparse;

    auto w = appender!string;
    renderStarterConfig(w);
    auto text = w[].dup;

    // The starter is documentation until uncommented: stripped, it decodes
    // to the empty overlay.
    stripJsonc(text);
    auto r = fromJSON!(Sparse!HueConfig)(text);
    assert(!r.hasError, r.error.toString);
    assert(r.value == Sparse!HueConfig.init);

    // Descriptions and defaults come from the schema.
    assert(w[].canFind(`// Colour theme, by name`));
    assert(w[].canFind(`// "theme": "tokyo-night",`));
    assert(w[].canFind(`"appearance": {`));
    assert(w[].canFind(`// "tabWidth": 4,`));
    assert(w[].canFind(`// "delayMs": 200,`));
}

// ─────────────────────────────────────────────────────────────────────────────
// `config save` — persist session deltas into the user file (CFG11).
// ─────────────────────────────────────────────────────────────────────────────

/// The pretty strict-JSON text of a sparse overlay (unset fields omitted) —
/// what `saveUserConfig` writes, and what a refusal shows to paste.
string sparseText(in Sparse!HueConfig overlay) => sparseTextOf!HueConfig(overlay);

/**
Persists `existing ∪ deltas` as the user file. The `CFG11` precedence rule is
structural in the signature: `deltas` is diff(session now, session start)
expressed sparsely, so a value a CLI flag supplied but the user never touched
is absent and can never be baked into the file. A strict-JSON file is
machine-owned and rewritten; a JSONC one is refused with the snippet to paste
(`force` overwrites, destroying its comments).
*/
Expected!(void, SaveRefusal) saveUserConfig(string path,
    Sparse!HueConfig existing, Sparse!HueConfig deltas, bool force = false)
    => saveSparseConfig!HueConfig(path, existing, deltas, "hue", force);

// ─────────────────────────────────────────────────────────────────────────────
// Save tests.
// ─────────────────────────────────────────────────────────────────────────────

@("settings_io.saveUserConfig.freshAndRewrite")
@system unittest
{
    import sparkles.test_utils.tmpfs : TmpFS;
    import std.path : buildPath;

    auto fixture = TmpFS.create();
    // The file does not exist yet — `saveUserConfig` creating it is the
    // behaviour under test — so only the directory is prepared here.
    const path = buildPath(fixture.dir, "config.json");

    // Fresh: deltas alone become the file.
    Sparse!HueConfig deltas;
    deltas.appearance.theme = "builtin-dark";
    deltas.panes.viewer.tabWidth = 8;
    auto first = saveUserConfig(path, Sparse!HueConfig.init, deltas);
    assert(!first.hasError, first.hasError ? first.error.message : "");

    auto back = readJsoncFile!(Sparse!HueConfig)(path);
    assert(!back.hasError);
    assert(back.value.appearance.theme.get == "builtin-dark");
    assert(back.value.panes.viewer.tabWidth.get == 8);
    assert(back.value.panes.viewer.lineNumbers.isNull); // still sparse

    // Machine-owned rewrite: new deltas win, prior settings survive.
    Sparse!HueConfig next;
    next.panes.viewer.tabWidth = 2;
    next.behaviour.liveTypes = false;
    auto second = saveUserConfig(path, back.value, next);
    assert(!second.hasError);
    auto again = readJsoncFile!(Sparse!HueConfig)(path);
    assert(again.value.appearance.theme.get == "builtin-dark"); // kept
    assert(again.value.panes.viewer.tabWidth.get == 2);         // toggled
    assert(again.value.behaviour.liveTypes.get == false);       // added
}

@("settings_io.saveUserConfig.refusesHumanOwned")
@system unittest
{
    import std.algorithm.searching : canFind;
    import sparkles.test_utils.tmpfs : TmpFS;

    auto fixture = TmpFS.create();
    const path = fixture.writeFileAt("config.json",
        "{\n  // my carefully commented file\n  \"appearance\": { \"theme\": \"x\" }\n}\n");

    Sparse!HueConfig deltas;
    deltas.panes.viewer.tabWidth = 2;

    auto refused = saveUserConfig(path, Sparse!HueConfig.init, deltas);
    assert(refused.hasError);
    assert(refused.error.kind == SaveRefusal.Kind.humanOwned);
    // The refusal is instructive: it names the file and carries the snippet.
    assert(refused.error.message.canFind(path));
    assert(refused.error.message.canFind(`"tabWidth": 2`), refused.error.message);

    // The file was untouched.
    auto still = readJsoncFile!(Sparse!HueConfig)(path);
    assert(still.value.appearance.theme.get == "x");
    assert(still.value.panes.viewer.tabWidth.isNull);

    // force overwrites, explicitly and destructively.
    auto forced = saveUserConfig(path, still.value, deltas, force: true);
    assert(!forced.hasError);
    auto after = readJsoncFile!(Sparse!HueConfig)(path);
    assert(after.value.appearance.theme.get == "x");
    assert(after.value.panes.viewer.tabWidth.get == 2);
}
