/**
hue's **shared web assets**: the one stylesheet a whole set of pre-rendered
pages links instead of each embedding its own copy
([`HTM1`](../../../docs/specs/hue/feature-requirements.md),
[`DEF5`](../../../docs/specs/hue/feature-requirements.md)).

A single `--html` document is self-contained — it carries a `<style>` block
(`FragmentOptions.embedStyles`). Hundreds of them must not: the theme sheet is
~2.6 KB, and the twoslash overlay another ~11.6 KB, per page. Those rules move
here, into one file the pages link.

$(B Light and dark in one sheet.) `renderHtml` emits class names, never
colours, so the $(I same) markup can be styled by two themes: this writes the
light theme's rules unscoped and the dark theme's under
$(LREF StylesheetContent.darkScope) (`html.dark ` — what VitePress toggles).
The scoped rules win by specificity, so the switch is a class on `<html>` and
nothing about the rendered pages changes. That is deliberately $(I not) the
CSS-variable multi-theme mode `DEF5` sketched: variables would put a
`var(--…)` indirection in every span and make the markup theme-aware for no
gain here.

Structure: $(B one pure string builder + one I/O seam) — $(LREF themeStylesheet)
builds the text, $(LREF writeStylesheetAsset) is the only thing that touches
disk.
*/
module web_assets;

import std.array : appender;

import sparkles.syntax;
import sparkles.twoslash : writeTwoslashStyles;

/// What goes into the shared stylesheet.
struct StylesheetContent
{
    /// scope selector for the dark theme's rules — include the trailing
    /// separator; `html.dark ` is the switch VitePress already toggles
    const(char)[] darkScope = "html.dark ";

    /// the page chrome a fragment needs outside `gallery.pageShell`: the
    /// `pre.syn-root` padding and the `--hue-gutter` line-number rules
    bool chrome = true;

    /// the `.twoslash-*` overlay rules (theme-independent chrome — emitted
    /// once, unscoped)
    bool twoslash;

    /// the prose / callout / table rules the markdown preview needs (`HTM5`)
    bool markdown;
}

/**
The shared stylesheet: `light`'s rules unscoped, then `dark`'s under
`content.darkScope`, then the requested chrome.

Pass `ResolvedTheme.init` for `dark` (the default) for a single-theme sheet —
an empty theme contributes no rules, so the output is simply the light half.
*/
string themeStylesheet(in ResolvedTheme light, in ResolvedTheme dark = ResolvedTheme.init,
    in StylesheetContent content = StylesheetContent.init) @safe pure
{
    auto w = appender!string;
    w ~= "/* Generated by hue. Syntax token colours: sparkles:syntax themes. */\n";
    writeThemeStylesheet(light, w);
    if (dark.labels.length || !dark.defaults.empty)
    {
        w ~= "\n/* Dark theme: same markup, scoped rules win on specificity. */\n";
        writeThemeStylesheet(dark, w, StylesheetOptions(scopeSelector: content.darkScope));
    }
    if (content.chrome)
    {
        w ~= "\n";
        w ~= chromeCss;
    }
    if (content.markdown)
    {
        w ~= "\n";
        w ~= markdownPreviewCss;
    }
    if (content.twoslash)
    {
        w ~= "\n";
        writeTwoslashStyles(w);
    }
    return w[];
}

/**
Prose + callout + table styling for the markdown HTML preview (`HTM5`),
layered over the theme's syntax stylesheet (`.syn-root` carries the page
fg/bg). Callout accents mirror the GUI preview
(blue / green / purple / yellow / red).
*/
enum markdownPreviewCss =
    ".md { max-width: 48em; margin: 2rem auto; padding: 0 1rem; line-height: 1.6; }\n" ~
    ".md pre.code-fence { padding: .75em 1em; overflow-x: auto; border-radius: 6px; }\n" ~
    ".md :not(pre) > code { padding: .1em .35em; border-radius: 3px; background: #8882; }\n" ~
    ".md blockquote { border-left: 3px solid #8888; margin: 1em 0; padding: 0 1em; opacity: .85; }\n" ~
    ".md table { border-collapse: collapse; margin: 1em 0; }\n" ~
    ".md th, .md td { border: 1px solid #8884; padding: .3em .6em; }\n" ~
    ".md img { max-width: 100%; }\n" ~
    ".callout { border-left: 4px solid; margin: 1em 0; padding: .1em 1em; border-radius: 4px; background: #8881; }\n" ~
    ".callout-title { font-weight: 600; margin: .4em 0; }\n" ~
    ".callout-note { border-color: #539bf5; }\n" ~
    ".callout-tip { border-color: #57ab5a; }\n" ~
    ".callout-important { border-color: #986ee2; }\n" ~
    ".callout-warning { border-color: #c69026; }\n" ~
    ".callout-caution { border-color: #e5534b; }\n";

/**
The page chrome for a fragment rendered without `gallery.pageShell`.

The gutter width is per-document, so it rides on the `<pre>` as `--hue-gutter`
(`gallery.FragmentOptions.gutter` writes it) and every rule here reads it back
— that is what lets one static sheet number documents of any length. The
number colour is `currentColor` at low opacity rather than a literal, so it
follows whichever theme is active instead of needing a scoped copy.
*/
private enum chromeCss =
    "pre.syn-root { padding: 1em; overflow-x: auto; }\n" ~
    "pre.syn-root > code { display: block; counter-reset: lineno;\n" ~
    "                      padding-left: var(--hue-gutter, 3ch); }\n" ~
    ".syn-root .ln { position: relative; counter-increment: lineno; }\n" ~
    ".syn-root .ln::before { content: counter(lineno); position: absolute;\n" ~
    "                        left: calc(-1 * var(--hue-gutter, 3ch));\n" ~
    "                        width: calc(var(--hue-gutter, 3ch) - 1ch);\n" ~
    "                        text-align: right; opacity: 0.45;\n" ~
    "                        -webkit-user-select: none; user-select: none; }\n";

/// The path a stylesheet asset is written to under a gallery's output
/// directory — also the href its pages link
/// (`gallery.GalleryOptions.stylesheetHref`), so the two stay one constant.
enum stylesheetAssetPath = "assets/hue.css";

/**
Writes `css` to `path`, creating its directory, and returns `path`. The only
I/O in this module.
*/
string writeStylesheetFile(string path, scope const(char)[] css) @system
{
    import std.file : mkdirRecurse, write;
    import std.path : dirName;

    const dir = path.dirName;
    if (dir.length)
        mkdirRecurse(dir);
    write(path, css);
    return path;
}

/// $(LREF writeStylesheetFile) at $(LREF stylesheetAssetPath) under `outDir`.
string writeStylesheetAsset(string outDir, scope const(char)[] css) @system
{
    import std.path : buildPath;

    return writeStylesheetFile(buildPath(outDir, stylesheetAssetPath), css);
}

// ---------------------------------------------------------------------------

version (unittest)
{
    private ResolvedTheme testTheme(string name, ubyte r) @safe pure nothrow
    {
        return resolveTheme(Theme(
            name: name,
            defaultFg: Color.fromRgb(r, 0x10, 0x10),
            defaultBg: Color.fromRgb(r, 0x20, 0x20),
            rules: [ThemeRule("keyword", StyleSpec(fg: Color.fromRgb(r, 0x30, 0x30)))]),
            LabelSet.fromNames(["keyword"]));
    }
}

/// Both themes land in one sheet and only the dark half is scoped — the
/// property the whole light/dark story rests on.
@("web_assets.themeStylesheet.darkHalfIsScoped")
@safe pure
unittest
{
    import std.algorithm.searching : canFind;

    const css = themeStylesheet(testTheme("light", 0xaa), testTheme("dark", 0xbb));

    assert(css.canFind(".syn-root{color:#aa1010;background-color:#aa2020}"), css);
    assert(css.canFind("html.dark .syn-root{color:#bb1010;background-color:#bb2020}"), css);
    assert(css.canFind(".syn-keyword{color:#aa3030}"), css);
    assert(css.canFind("html.dark .syn-keyword{color:#bb3030}"), css);

    // No dark rule may escape its scope: every `#bb…` declaration must sit in a
    // rule whose selector is scoped. Checked per line, since that is how
    // `writeThemeStylesheet` emits them.
    foreach (line; css.lines)
        if (line.canFind("#bb"))
            assert(line.canFind("html.dark "), line);
}

/// A single-theme sheet is just the light half — nothing is scoped, so a page
/// that never toggles `html.dark` pays nothing for the feature.
@("web_assets.themeStylesheet.singleTheme")
@safe pure
unittest
{
    import std.algorithm.searching : canFind;

    const css = themeStylesheet(testTheme("light", 0xaa));
    assert(!css.canFind("html.dark"), css);
    assert(css.canFind(".syn-keyword{color:#aa3030}"), css);
}

/// The chrome reads the per-document gutter width off the `<pre>`, so one
/// static sheet numbers documents of any length; the twoslash overlay is
/// opt-in (it is ~11.6 KB that a plain listing never needs).
@("web_assets.themeStylesheet.chromeAndTwoslashAreOptional")
@safe pure
unittest
{
    import std.algorithm.searching : canFind;
    import gallery : gutterProperty;

    const full = themeStylesheet(testTheme("light", 0xaa), ResolvedTheme.init,
        StylesheetContent(twoslash: true));
    assert(full.canFind("var(" ~ gutterProperty[0 .. $ - 1] ~ ", 3ch)"), full);
    assert(full.canFind("counter-increment: lineno"), full);
    assert(full.canFind(".twoslash-hover"), full);

    const bare = themeStylesheet(testTheme("light", 0xaa), ResolvedTheme.init,
        StylesheetContent(chrome: false));
    assert(!bare.canFind("lineno"), bare);
    assert(!bare.canFind(".twoslash-hover"), bare);
}

/// The chrome's custom-property name must be the one the fragment writes —
/// they are set in two different modules and only agree by this test.
@("web_assets.chromeCss.matchesTheFragmentProperty")
@safe pure
unittest
{
    import std.algorithm.searching : canFind;
    import gallery : FragmentOptions, gutterProperty;

    // `gutterProperty` is `--hue-gutter:` (declaration form); the sheet reads
    // the same name back through `var()`.
    assert(gutterProperty[$ - 1] == ':');
    assert(chromeCss.canFind("var(" ~ gutterProperty[0 .. $ - 1]), chromeCss);
}

version (unittest)
private const(char)[][] lines(string s) @safe pure nothrow
{
    const(char)[][] outp;
    size_t start;
    foreach (i, char c; s)
        if (c == '\n')
        {
            outp ~= s[start .. i];
            start = i + 1;
        }
    if (start < s.length)
        outp ~= s[start .. $];
    return outp;
}
