/// Public import surface for the `utf8proc` ([JuliaStrings/utf8proc](https://github.com/JuliaStrings/utf8proc))
/// bindings.
///
/// The raw ImportC declarations live in `sparkles.utf8proc.utf8proc_c`
/// (generated by compiling `utf8proc_c.c`, which `#include`s `<utf8proc.h>`).
/// Import this package to pull them in as `import sparkles.utf8proc;`.
///
/// Note: the shim is `utf8proc_c.c`, not the usual `c.c`, because ImportC names
/// a module by its file *stem* — two `c.c` shims would both become module `c`
/// and collide when a build links more than one binding (e.g. this and
/// `sparkles.ghostty`). A unique stem per shim avoids that.
module sparkles.utf8proc;

public import sparkles.utf8proc.utf8proc_c;
