// xdg-shell windowing scaffold — the full "first window" handshake that the
// minimal ../../example/app.d deliberately stops short of. It opens a real
// toplevel window titled "wsi-scaffold" and exercises the complete Wayland
// pixel pipeline:
//
//   wl_display → wl_registry → bind {wl_compositor, wl_shm, xdg_wm_base, wl_seat}
//   → wl_surface → xdg_surface → xdg_toplevel → initial *no-buffer* commit
//   → xdg_surface.configure → ack_configure → wl_shm double-buffered ARGB
//   gradient → wl_surface.attach/damage_buffer/commit → wl_surface.frame
//   callbacks drive the redraw loop.
//
// Resize is negotiated, never imposed: every xdg_surface.configure is acked
// with its serial *before* the next commit, and the committed buffer is
// asserted to match the acked size (the F02 contract). Under WSI_AUTO_EXIT=1
// the demo drives its own resize storm — set_maximized at frame 30, unset at
// frame 60 — and exits 0 after ~120 frames (or ~2.5 s).
//
// The xdg-shell glue is generated by wayland-scanner (./generate.sh); the
// `static inline` request helpers are re-exported as `wsi_*` by the ImportC
// shim ./c.c. Instrumentation contract: ./instrument.d. Findings: ../../scaffold.md.
//
// Headless-safe: no compositor → SKIP, exit 0.
module app;

import c; // ImportC: <wayland-client.h> + xdg-shell glue + wsi_* wrappers
import instrument;
import core.stdc.stdio : printf;
import core.stdc.stdlib : getenv;
import core.stdc.string : strcmp;

// ----------------------------------------------------------------- tunables

enum int defaultWidth = 640; // used while the compositor lets us pick (0x0 configure)
enum int defaultHeight = 480;
enum int maximizeAtFrame = 30; // auto-exit choreography: resize storm …
enum int unmaximizeAtFrame = 60; // … and back
enum int autoExitFrames = 120; // ≈ 2 s at 60 Hz
enum long autoExitUsCap = 2_500_000; // wall-clock backstop

// -------------------------------------------------------------------- state

/// One wl_shm-backed ARGB8888 buffer. `busy` is owned by the compositor
/// between wl_surface.commit and the wl_buffer.release event.
struct Buffer
{
    wl_buffer* handle;
    uint* pixels; // mmap'ed, shared with the compositor
    size_t byteSize;
    int width, height;
    bool busy;
}

__gshared
{
    wl_display* g_display;
    wl_registry* g_registry;
    wl_compositor* g_compositor;
    wl_shm* g_shm;
    wl_seat* g_seat;
    xdg_wm_base* g_wmBase;
    wl_surface* g_surface;
    xdg_surface* g_xdgSurface;
    xdg_toplevel* g_toplevel;
    wl_callback* g_frameCb; // at most one outstanding frame callback

    Buffer[2] g_buffers; // double buffering: paint one while the other is on screen

    int g_width = defaultWidth; // last *acked* size — buffers must match it
    int g_height = defaultHeight;
    int g_pendingWidth; // from xdg_toplevel.configure (0 = client's choice)
    int g_pendingHeight;
    bool g_configured; // first configure acked (may attach buffers from now on)
    bool g_presented; // first frame callback after the first buffer commit
    bool g_running = true;
    bool g_autoExit;
    int g_frames; // frame callbacks received
    int g_commits; // buffer commits sent
}

// ---------------------------------------------------------- shm buffer pool

/// (Re)allocate `b` so it matches `w`×`h`. Only ever called on non-busy
/// buffers, so destroying a stale-sized wl_buffer here is race-free.
bool ensureBuffer(ref Buffer b, int w, int h) nothrow @nogc
{
    if (b.handle !is null && (b.width != w || b.height != h))
    {
        wsi_buffer_destroy(b.handle);
        munmap(b.pixels, b.byteSize);
        b = Buffer.init;
    }
    if (b.handle !is null)
        return true;

    immutable stride = w * 4;
    immutable size = cast(size_t)(stride) * h;
    immutable fd = memfd_create("wsi-scaffold", MFD_CLOEXEC);
    if (fd < 0)
        return false;
    if (ftruncate(fd, cast(long) size) != 0)
    {
        close(fd);
        return false;
    }
    void* mem = mmap(null, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (mem is cast(void*)-1)
    {
        close(fd);
        return false;
    }
    instrStep("memfd_create+mmap");

    // The pool can be destroyed right after create_buffer: the buffer keeps
    // the backing memory alive, and the compositor has dup'ed the fd.
    wl_shm_pool* pool = wsi_shm_create_pool(g_shm, fd, cast(int) size);
    instrStep("wl_shm_create_pool");
    b.handle = wsi_shm_pool_create_buffer(pool, 0, w, h, stride, WL_SHM_FORMAT_ARGB8888);
    instrStep("wl_shm_pool_create_buffer");
    wsi_shm_pool_destroy(pool);
    close(fd);
    wsi_buffer_add_listener(b.handle, &g_bufferListener, &b);

    b.pixels = cast(uint*) mem;
    b.byteSize = size;
    b.width = w;
    b.height = h;
    b.busy = false;
    instrEvent("buffer_alloc", "size=%dx%d bytes=%zu", w, h, size);
    return true;
}

/// Corner-anchored diagonal gradient (F02: geometry must visibly track the
/// window size) with a frame-driven blue channel so each redraw is observable.
void paint(ref Buffer b, int frame) nothrow @nogc
{
    immutable maxX = b.width > 1 ? b.width - 1 : 1;
    immutable maxY = b.height > 1 ? b.height - 1 : 1;
    immutable uint blue = (frame * 2) & 0xff;
    foreach (y; 0 .. b.height)
    {
        uint* row = b.pixels + cast(size_t) y * b.width;
        immutable uint g = cast(uint)(y * 255 / maxY) << 8;
        foreach (x; 0 .. b.width)
            row[x] = 0xff00_0000 | (cast(uint)(x * 255 / maxX) << 16) | g | blue;
    }
}

/// Paint into a free buffer and commit it, requesting the next frame callback.
/// Called from the first configure (first pixel), from later size-changing
/// configures, and from every frame callback.
void render() nothrow @nogc
{
    Buffer* buf = null;
    foreach (ref b; g_buffers)
        if (!b.busy)
        {
            buf = &b;
            break;
        }
    if (buf is null)
    {
        // Both buffers held by the compositor: drop this frame. The
        // wl_buffer.release handler re-renders as soon as one comes back.
        instrEvent("frame_skipped", "reason=all_buffers_busy");
        return;
    }
    if (!ensureBuffer(*buf, g_width, g_height))
    {
        g_running = false;
        return;
    }
    paint(*buf, g_frames);

    // F02 contract: the buffer we are about to commit matches the acked size.
    assert(buf.width == g_width && buf.height == g_height,
        "committed buffer size does not match the acked configure size");

    wsi_surface_attach(g_surface, buf.handle, 0, 0);
    wsi_surface_damage_buffer(g_surface, 0, 0, buf.width, buf.height);
    if (g_frameCb is null) // keep exactly one frame callback in flight
    {
        g_frameCb = wsi_surface_frame(g_surface);
        wsi_callback_add_listener(g_frameCb, &g_frameListener, null);
    }
    wsi_surface_commit(g_surface);
    buf.busy = true;
    g_commits++;
    if (g_commits == 1)
        instrEvent("first_commit", "size=%dx%d", buf.width, buf.height);
}

// ---------------------------------------------------------------- listeners
// All callbacks are `extern (C) nothrow @nogc` to match the listener
// function-pointer types the ImportC `#pragma attribute` stamped in c.c.

extern (C) void onGlobal(void* data, wl_registry* reg, uint name,
    const(char)* iface, uint ver) nothrow @nogc
{
    static uint capped(uint advertised, uint want) nothrow @nogc
    {
        return advertised < want ? advertised : want;
    }

    if (strcmp(iface, wl_compositor_interface.name) == 0)
        g_compositor = cast(wl_compositor*) wsi_registry_bind(reg, name,
            &wl_compositor_interface, capped(ver, 4)); // v4: wl_surface.damage_buffer
    else if (strcmp(iface, wl_shm_interface.name) == 0)
        g_shm = cast(wl_shm*) wsi_registry_bind(reg, name, &wl_shm_interface, 1);
    else if (strcmp(iface, xdg_wm_base_interface.name) == 0)
        g_wmBase = cast(xdg_wm_base*) wsi_registry_bind(reg, name, &xdg_wm_base_interface, 1);
    else if (strcmp(iface, wl_seat_interface.name) == 0)
        g_seat = cast(wl_seat*) wsi_registry_bind(reg, name, &wl_seat_interface,
            capped(ver, 2)); // v2: name event
    else
        return;
    instrEvent("step", "name=wl_registry_bind iface=%s version=%u", iface, ver);
}

extern (C) void onGlobalRemove(void* data, wl_registry* reg, uint name) nothrow @nogc
{
}

extern (C) void onWmBasePing(void* data, xdg_wm_base* b, uint serial) nothrow @nogc
{
    wsi_wm_base_pong(b, serial); // liveness check — answer or be killed
    instrEvent("ping_pong", "serial=%u", serial);
}

extern (C) void onSeatCapabilities(void* data, wl_seat* s, uint caps) nothrow @nogc
{
    instrEvent("seat_capabilities", "caps=0x%x", caps);
}

extern (C) void onSeatName(void* data, wl_seat* s, const(char)* name) nothrow @nogc
{
    instrEvent("seat_name", "name=%s", name);
}

/// xdg_toplevel.configure: the compositor *suggests* a size (0×0 = "you
/// pick"). Only latched here; it takes effect at xdg_surface.configure.
extern (C) void onToplevelConfigure(void* data, xdg_toplevel* t, int w, int h,
    wl_array* states) nothrow @nogc
{
    g_pendingWidth = w;
    g_pendingHeight = h;
    int maximized = 0;
    const start = cast(const(uint)*) states.data;
    foreach (i; 0 .. states.size / uint.sizeof)
        if (start[i] == XDG_TOPLEVEL_STATE_MAXIMIZED)
            maximized = 1;
    instrEvent("xdg_toplevel_configure", "size=%dx%d maximized=%d", w, h, maximized);
}

/// xdg_surface.configure: the atomic "apply everything" event. Protocol order
/// proven in the WAYLAND_DEBUG trace: ack_configure(serial) *then* the commit
/// of a buffer matching the new size.
extern (C) void onXdgSurfaceConfigure(void* data, xdg_surface* s, uint serial) nothrow @nogc
{
    immutable w = g_pendingWidth > 0 ? g_pendingWidth : defaultWidth;
    immutable h = g_pendingHeight > 0 ? g_pendingHeight : defaultHeight;
    instrEvent("configure", "serial=%u size=%dx%d", serial, w, h);

    wsi_xdg_surface_ack_configure(s, serial);
    instrStep("xdg_surface_ack_configure");

    immutable resized = w != g_width || h != g_height;
    g_width = w;
    g_height = h;

    if (!g_configured)
    {
        g_configured = true;
        instrFirstConfigure();
        render(); // the first buffer commit — the window becomes visible
    }
    else if (resized)
    {
        instrResize(w, h, 1); // no fractional-scale binding in the scaffold
        render(); // commit a matching buffer right away, don't wait a frame
    }
}

extern (C) void onToplevelClose(void* data, xdg_toplevel* t) nothrow @nogc
{
    instrCloseRequested();
    g_running = false;
}

// Bound at xdg_wm_base v1, so these v4/v5 events never arrive; the listener
// struct generated from wayland-protocols 1.47 still has the slots to fill.
extern (C) void onToplevelConfigureBounds(void* data, xdg_toplevel* t, int w, int h) nothrow @nogc
{
}

extern (C) void onToplevelWmCapabilities(void* data, xdg_toplevel* t, wl_array* caps) nothrow @nogc
{
}

/// wl_buffer.release: the compositor no longer reads the buffer; reuse it.
extern (C) void onBufferRelease(void* data, wl_buffer* b) nothrow @nogc
{
    auto buf = cast(Buffer*) data;
    buf.busy = false;
    // If a frame was dropped because both buffers were busy, recover here.
    if (g_running && g_configured && g_frameCb is null)
        render();
}

/// wl_surface.frame `done`: the compositor presented the surface and is ready
/// for the next frame — the vsync-paced redraw driver.
extern (C) void onFrameDone(void* data, wl_callback* cb, uint timeMs) nothrow @nogc
{
    wsi_callback_destroy(cb); // one-shot object
    g_frameCb = null;
    g_frames++;
    instrFrameCallback(timeMs);

    if (!g_presented)
    {
        g_presented = true;
        // First pixel confirmed: a post-ack buffer commit has been presented.
        instrFirstPixelPresented();
    }

    if (g_autoExit)
    {
        if (g_frames == maximizeAtFrame)
        {
            wsi_toplevel_set_maximized(g_toplevel);
            instrStep("xdg_toplevel_set_maximized");
        }
        else if (g_frames == unmaximizeAtFrame)
        {
            wsi_toplevel_unset_maximized(g_toplevel);
            instrStep("xdg_toplevel_unset_maximized");
        }
        if (g_frames >= autoExitFrames || instrNowUs() > autoExitUsCap)
        {
            g_running = false;
            return;
        }
    }
    render();
}

__gshared wl_registry_listener g_registryListener = {&onGlobal, &onGlobalRemove};
__gshared xdg_wm_base_listener g_wmBaseListener = {&onWmBasePing};
__gshared wl_seat_listener g_seatListener = {&onSeatCapabilities, &onSeatName};
__gshared xdg_surface_listener g_xdgSurfaceListener = {&onXdgSurfaceConfigure};
__gshared xdg_toplevel_listener g_toplevelListener = {
    &onToplevelConfigure, &onToplevelClose,
    &onToplevelConfigureBounds, &onToplevelWmCapabilities
};
__gshared wl_buffer_listener g_bufferListener = {&onBufferRelease};
__gshared wl_callback_listener g_frameListener = {&onFrameDone};

// ----------------------------------------------------------------- teardown

void teardown() nothrow @nogc
{
    instrEvent("teardown_start");
    foreach (ref b; g_buffers)
        if (b.handle !is null)
        {
            wsi_buffer_destroy(b.handle);
            munmap(b.pixels, b.byteSize);
            b = Buffer.init;
        }
    if (g_frameCb !is null)
        wsi_callback_destroy(g_frameCb);
    if (g_toplevel !is null)
        wsi_toplevel_destroy(g_toplevel);
    if (g_xdgSurface !is null)
        wsi_xdg_surface_destroy(g_xdgSurface);
    if (g_surface !is null)
        wsi_surface_destroy(g_surface);
    if (g_wmBase !is null)
        wsi_wm_base_destroy(g_wmBase);
    // The remaining globals have no destructor request at the bound versions;
    // destroying the client-side proxy is the correct cleanup.
    if (g_seat !is null)
        wl_proxy_destroy(cast(wl_proxy*) g_seat);
    if (g_shm !is null)
        wl_proxy_destroy(cast(wl_proxy*) g_shm);
    if (g_compositor !is null)
        wl_proxy_destroy(cast(wl_proxy*) g_compositor);
    if (g_registry !is null)
        wl_proxy_destroy(cast(wl_proxy*) g_registry);
    wl_display_disconnect(g_display);
    instrEvent("teardown_done");
}

// --------------------------------------------------------------------- main

int main()
{
    instrInit("scaffold-wayland");
    const autoEnv = getenv("WSI_AUTO_EXIT");
    g_autoExit = autoEnv !is null && *autoEnv == '1';

    // 1. Connect (SKIP cleanly on headless hosts without a compositor).
    g_display = wl_display_connect(null);
    if (g_display is null)
    {
        printf("SKIP: no Wayland compositor (wl_display_connect returned null)\n");
        return 0;
    }
    instrStep("wl_display_connect");

    // 2. Registry: discover and bind the four globals a window needs.
    g_registry = wsi_display_get_registry(g_display);
    instrStep("wl_display_get_registry");
    wsi_registry_add_listener(g_registry, &g_registryListener, null);
    wl_display_roundtrip(g_display); // blocks; onGlobal binds during this
    instrStep("wl_display_roundtrip");

    if (g_compositor is null || g_shm is null || g_wmBase is null)
    {
        printf("SKIP: compositor lacks a required global (wl_compositor/wl_shm/xdg_wm_base)\n");
        teardown();
        return 0;
    }
    wsi_wm_base_add_listener(g_wmBase, &g_wmBaseListener, null);
    if (g_seat !is null)
        wsi_seat_add_listener(g_seat, &g_seatListener, null);

    // 3. Build the window object tree: wl_surface → xdg_surface → xdg_toplevel.
    g_surface = wsi_compositor_create_surface(g_compositor);
    instrStep("wl_compositor_create_surface");
    g_xdgSurface = wsi_wm_base_get_xdg_surface(g_wmBase, g_surface);
    instrStep("xdg_wm_base_get_xdg_surface");
    wsi_xdg_surface_add_listener(g_xdgSurface, &g_xdgSurfaceListener, null);
    g_toplevel = wsi_xdg_surface_get_toplevel(g_xdgSurface);
    instrStep("xdg_surface_get_toplevel");
    wsi_toplevel_add_listener(g_toplevel, &g_toplevelListener, null);
    wsi_toplevel_set_title(g_toplevel, "wsi-scaffold");
    instrStep("xdg_toplevel_set_title");
    wsi_toplevel_set_app_id(g_toplevel, "wsi-scaffold");
    instrStep("xdg_toplevel_set_app_id");
    instrWindowCreated();

    // 4. The mandatory initial commit *without* a buffer (attaching one before
    //    the first configure is a protocol error). The compositor answers with
    //    the first xdg_surface.configure; the first pixel happens in its handler.
    wsi_surface_commit(g_surface);
    instrStep("wl_surface_commit");

    // 5. Event loop. wl_display_dispatch flushes requests, blocks on the
    //    socket, and dispatches a batch of events; the listeners above do all
    //    the work. Frame callbacks keep the loop ticking ~60 Hz.
    while (g_running && wl_display_dispatch(g_display) != -1)
    {
        if (g_autoExit && instrNowUs() > autoExitUsCap + 2_000_000)
            g_running = false; // hard backstop if frame callbacks ever stall
    }

    // 6. Clean teardown: buffers → frame callback → role objects → surface →
    //    globals → registry → disconnect (children before parents).
    teardown();
    printf("ok: presented %d frames in %d commits, final size %dx%d\n",
        g_frames, g_commits, g_width, g_height);
    return 0;
}
