/**
hue's **shared web assets**: the one stylesheet a whole set of pre-rendered
pages links instead of each embedding its own copy
([`HTM1`](../../../../../docs/specs/hue/feature-requirements.md),
[`DEF5`](../../../../../docs/specs/hue/feature-requirements.md)).

A single `--html` document is self-contained — it carries a `<style>` block
(`FragmentOptions.embedStyles`). Hundreds of them must not: the theme sheet is
~2.6 KB, and the twoslash overlay another ~11.6 KB, per page. Those rules move
here, into one file the pages link.

$(B Light and dark in one sheet.) `renderHtml` emits class names, never
colours, so the $(I same) markup can be styled by two themes: this writes the
light theme's rules unscoped and the dark theme's under
$(LREF StylesheetContent.darkScope) (`html.dark ` — what VitePress toggles).
The scoped rules win by specificity, so the switch is a class on `<html>` and
nothing about the rendered pages changes. That is deliberately $(I not) the
CSS-variable multi-theme mode `DEF5` sketched: variables would put a
`var(--…)` indirection in every span and make the markup theme-aware for no
gain here.

Structure: $(B one pure string builder + one I/O seam) — $(LREF themeStylesheet)
builds the text, $(LREF writeStylesheetAsset) is the only thing that touches
disk.
*/
module sparkles.docs.assets;

import std.array : appender;

import sparkles.syntax;
import sparkles.twoslash : writeTwoslashStyles;
import sparkles.ui.css : writeThemeProperties;
import sparkles.ui.dtcg : DtcgResult;
import sparkles.ui.style : ColorScheme, defaultTwoslashPalette, Slot;
import sparkles.ui.theme : Theme;
import sparkles.ui.theme_file : ThemeFile;
import sparkles.ui.tokens : ColorChannel, cssName;

/// What goes into the shared stylesheet.
struct StylesheetContent
{
    /// scope selector for the dark theme's rules — include the trailing
    /// separator; `html.dark ` is the switch VitePress already toggles
    const(char)[] darkScope = "html.dark ";

    /// the page chrome a fragment needs outside `gallery.pageShell`: the
    /// `pre.syn-root` padding and the `--hue-gutter` line-number rules
    bool chrome = true;

    /// the `.twoslash-*` overlay rules (theme-independent chrome — emitted
    /// once, unscoped)
    bool twoslash;

    /// the prose / callout / table rules the markdown preview needs (`HTM5`)
    bool markdown;
}

/**
The shared stylesheet: `light`'s rules unscoped, then `dark`'s under
`content.darkScope`, then the requested chrome.

Pass `ResolvedTheme.init` for `dark` (the default) for a single-theme sheet —
an empty theme contributes no rules, so the output is simply the light half.
*/
string themeStylesheet(in ResolvedTheme light, in ResolvedTheme dark = ResolvedTheme.init,
    in StylesheetContent content = StylesheetContent.init) @safe pure
{
    auto w = appender!string;
    w ~= "/* Generated by hue. Syntax token colours: sparkles:syntax themes. */\n";
    writeThemeStylesheet(light, w);
    if (dark.labels.length || !dark.defaults.empty)
    {
        w ~= "\n/* Dark theme: same markup, scoped rules win on specificity. */\n";
        writeThemeStylesheet(dark, w, StylesheetOptions(scopeSelector: content.darkScope));
    }
    if (content.chrome)
    {
        w ~= "\n";
        w ~= chromeCss;
    }
    if (content.markdown)
    {
        w ~= "\n";
        w ~= markdownPreviewCss;
    }
    if (content.twoslash)
    {
        w ~= "\n";
        writeTwoslashStyles(w);
    }
    return w[];
}

/**
Prose + callout + table styling for the markdown HTML preview (`HTM5`),
layered over the theme's syntax stylesheet (`.syn-root` carries the page
fg/bg). Each callout's accent is a status token (`WEB2`): see
$(LREF calloutSlots).
*/
enum markdownPreviewCss =
    ".md { max-width: 48em; margin: 2rem auto; padding: 0 1rem; line-height: 1.6; }\n" ~
    ".md pre.code-fence { padding: .75em 1em; overflow-x: auto; border-radius: 6px; }\n" ~
    ".md :not(pre) > code { padding: .1em .35em; border-radius: 3px; background: #8882; }\n" ~
    ".md blockquote { border-left: 3px solid #8888; margin: 1em 0; padding: 0 1em; opacity: .85; }\n" ~
    ".md table { border-collapse: collapse; margin: 1em 0; }\n" ~
    ".md th, .md td { border: 1px solid #8884; padding: .3em .6em; }\n" ~
    ".md img { max-width: 100%; }\n" ~
    ".callout { border-left: 4px solid; margin: 1em 0; padding: .1em 1em; border-radius: 4px; background: #8881; }\n" ~
    ".callout-title { font-weight: 600; margin: .4em 0; }\n" ~
    calloutCss();

/**
The slot each GitHub callout kind takes its accent from (`WEB2`): the status
roles, and the second accent for `important`, which has no status of its own.
*/
enum Slot[string] calloutSlots = [
    "note": Slot.info,
    "tip": Slot.success,
    "important": Slot.accentSecondary,
    "warning": Slot.warn,
    "caution": Slot.error,
];

/// The callout rules: each reads its slot's foreground property, falling back
/// to the default dark palette's value for a page that links no token sheet
/// (a lone `--html` document), so no accent is typed here by hand.
private string calloutCss() @safe pure
{
    import std.format : format;

    const pal = defaultTwoslashPalette(ColorScheme.dark);
    string s;
    foreach (kind; ["note", "tip", "important", "warning", "caution"])
    {
        const slot = calloutSlots[kind];
        const c = pal.fg[slot].rgb;
        s ~= format(".callout-%s { border-color: var(%s, #%02x%02x%02x); }\n",
            kind, cssName(slot, ColorChannel.foreground), c.r, c.g, c.b);
    }
    return s;
}

/// Where a token stylesheet's dark values apply (`WEB2`).
struct TokenSheetOptions
{
    /// the selector the dark values sit under — what VitePress toggles
    const(char)[] darkScope = "html.dark";

    /// also apply the dark values under `prefers-color-scheme: dark`, for a
    /// page with no toggle of its own; a site that toggles a class leaves it
    /// off, or the system's choice would override the reader's
    bool followSystem;
}

/**
The design system's custom properties for a theme pair (`WEB1`, `WEB2`): the
light theme's values on `:root`, the dark theme's under `o.darkScope` (and
`prefers-color-scheme: dark` when `o.followSystem`). Every name comes from
$(REF cssPropertyName, sparkles,ui,css); nothing here names a token. `T` is a
$(REF Theme, sparkles,ui,theme) or a loaded
$(REF ThemeFile, sparkles,ui,theme_file), whose own tokens come along.
*/
string tokenStylesheet(T)(const T light, const T dark,
    in TokenSheetOptions o = TokenSheetOptions.init)
if (is(T == Theme) || is(T == ThemeFile))
{
    auto w = appender!string;
    w ~= "/* Generated by sparkles:docs from the themes \"" ~ nameOf(light) ~ "\" and \""
        ~ nameOf(dark) ~ "\" (design-system WEB2). Do not edit. */\n";
    w ~= ":root {\n";
    writeThemeProperties(w, light);
    w ~= "}\n\n";
    w ~= o.darkScope;
    w ~= " {\n";
    writeThemeProperties(w, dark);
    w ~= "}\n";
    if (o.followSystem)
    {
        w ~= "\n@media (prefers-color-scheme: dark) {\n  :root {\n";
        writeThemeProperties(w, dark, "    ");
        w ~= "  }\n}\n";
    }
    return w[];
}

/// ditto, one theme: its values on `:root`, nothing scoped.
string tokenStylesheet(T)(const T only)
if (is(T == Theme) || is(T == ThemeFile))
{
    auto w = appender!string;
    w ~= "/* Generated by sparkles:docs from the theme \"" ~ nameOf(only)
        ~ "\" (design-system WEB2). Do not edit. */\n:root {\n";
    writeThemeProperties(w, only);
    w ~= "}\n";
    return w[];
}

/// The docs site's two theme files (`WEB3`), relative to the repository root:
/// seeds holding the site's own values until the Sparkles theme replaces them.
enum string[2] siteThemePaths = [
    "docs/.vitepress/theme/sparkles-light.tokens",
    "docs/.vitepress/theme/sparkles-dark.tokens",
];

/// Where the site's generated stylesheet is committed, relative to the root.
enum siteStylesheetPath = "docs/.vitepress/theme/spk.css";

/**
The docs site's stylesheet (`WEB3`): the properties of the theme files at
$(LREF siteThemePaths) under `root`, the dark half under `html.dark` only,
since VitePress toggles that class and follows the system itself.
*/
DtcgResult!string siteStylesheet(string root) @safe
{
    import std.path : buildPath;
    import expected : ok;
    import sparkles.ui.dtcg : DtcgError;
    import sparkles.ui.theme_file : loadThemeFile;

    auto light = loadThemeFile(buildPath(root, siteThemePaths[0]));
    if (light.hasError)
        return typeof(return)(light.error);
    auto dark = loadThemeFile(buildPath(root, siteThemePaths[1]));
    if (dark.hasError)
        return typeof(return)(dark.error);
    return ok!DtcgError(tokenStylesheet(light.value, dark.value));
}

private string nameOf(const Theme t) @safe pure nothrow @nogc => t.name;
private string nameOf(const ThemeFile f) @safe pure nothrow @nogc => f.theme.name;

/**
The page chrome for a fragment rendered without `gallery.pageShell`.

The gutter width is per-document, so it rides on the `<pre>` as `--hue-gutter`
(`gallery.FragmentOptions.gutter` writes it) and every rule here reads it back
— that is what lets one static sheet number documents of any length. The
number colour is `currentColor` at low opacity rather than a literal, so it
follows whichever theme is active instead of needing a scoped copy.
*/
private enum chromeCss =
    "pre.syn-root { padding: 1em; overflow-x: auto; }\n" ~
    "pre.syn-root > code { display: block; counter-reset: lineno;\n" ~
    "                      padding-left: var(--hue-gutter, 3ch); }\n" ~
    ".syn-root .ln { position: relative; counter-increment: lineno; }\n" ~
    ".syn-root .ln::before { content: counter(lineno); position: absolute;\n" ~
    "                        left: calc(-1 * var(--hue-gutter, 3ch));\n" ~
    "                        width: calc(var(--hue-gutter, 3ch) - 1ch);\n" ~
    "                        text-align: right; opacity: 0.45;\n" ~
    "                        -webkit-user-select: none; user-select: none; }\n";

/// The path a stylesheet asset is written to under a gallery's output
/// directory — also the href its pages link
/// (`gallery.GalleryOptions.stylesheetHref`), so the two stay one constant.
enum stylesheetAssetPath = "assets/hue.css";

/**
Writes `css` to `path`, creating its directory, and returns `path`. The only
I/O in this module.
*/
string writeStylesheetFile(string path, scope const(char)[] css) @system
{
    import std.file : mkdirRecurse, write;
    import std.path : dirName;

    const dir = path.dirName;
    if (dir.length)
        mkdirRecurse(dir);
    write(path, css);
    return path;
}

/// $(LREF writeStylesheetFile) at $(LREF stylesheetAssetPath) under `outDir`.
string writeStylesheetAsset(string outDir, scope const(char)[] css) @system
{
    import std.path : buildPath;

    return writeStylesheetFile(buildPath(outDir, stylesheetAssetPath), css);
}

// ---------------------------------------------------------------------------

version (unittest)
{
    private ResolvedTheme testTheme(string name, ubyte r) @safe pure nothrow
    {
        return resolveTheme(SyntaxTheme(
            name: name,
            defaultFg: Color.fromRgb(r, 0x10, 0x10),
            defaultBg: Color.fromRgb(r, 0x20, 0x20),
            rules: [ThemeRule("keyword", StyleSpec(fg: Color.fromRgb(r, 0x30, 0x30)))]),
            LabelSet.fromNames(["keyword"]));
    }
}

/// Both themes land in one sheet and only the dark half is scoped — the
/// property the whole light/dark story rests on.
@("web_assets.themeStylesheet.darkHalfIsScoped")
@safe pure
unittest
{
    import std.algorithm.searching : canFind;

    const css = themeStylesheet(testTheme("light", 0xaa), testTheme("dark", 0xbb));

    assert(css.canFind(".syn-root{color:#aa1010;background-color:#aa2020}"), css);
    assert(css.canFind("html.dark .syn-root{color:#bb1010;background-color:#bb2020}"), css);
    assert(css.canFind(".syn-keyword{color:#aa3030}"), css);
    assert(css.canFind("html.dark .syn-keyword{color:#bb3030}"), css);

    // No dark rule may escape its scope: every `#bb…` declaration must sit in a
    // rule whose selector is scoped. Checked per line, since that is how
    // `writeThemeStylesheet` emits them.
    foreach (line; css.lines)
        if (line.canFind("#bb"))
            assert(line.canFind("html.dark "), line);
}

/// A single-theme sheet is just the light half — nothing is scoped, so a page
/// that never toggles `html.dark` pays nothing for the feature.
@("web_assets.themeStylesheet.singleTheme")
@safe pure
unittest
{
    import std.algorithm.searching : canFind;

    const css = themeStylesheet(testTheme("light", 0xaa));
    assert(!css.canFind("html.dark"), css);
    assert(css.canFind(".syn-keyword{color:#aa3030}"), css);
}

/// The chrome reads the per-document gutter width off the `<pre>`, so one
/// static sheet numbers documents of any length; the twoslash overlay is
/// opt-in (it is ~11.6 KB that a plain listing never needs).
@("web_assets.themeStylesheet.chromeAndTwoslashAreOptional")
@safe pure
unittest
{
    import std.algorithm.searching : canFind;
    import sparkles.docs.fragment : gutterProperty;

    const full = themeStylesheet(testTheme("light", 0xaa), ResolvedTheme.init,
        StylesheetContent(twoslash: true));
    assert(full.canFind("var(" ~ gutterProperty[0 .. $ - 1] ~ ", 3ch)"), full);
    assert(full.canFind("counter-increment: lineno"), full);
    assert(full.canFind(".twoslash-hover"), full);

    const bare = themeStylesheet(testTheme("light", 0xaa), ResolvedTheme.init,
        StylesheetContent(chrome: false));
    assert(!bare.canFind("lineno"), bare);
    assert(!bare.canFind(".twoslash-hover"), bare);
}

/// The light values sit on `:root` and the dark ones only under the toggle,
/// unless the page follows the system — what a page with no toggle needs.
@("web_assets.tokenStylesheet.darkValuesAreScoped")
@safe unittest
{
    import std.algorithm.searching : canFind, count;
    import sparkles.ui.themes : builtinThemes;

    const light = builtinThemes["github-light"], dark = builtinThemes["github-dark"];
    const css = tokenStylesheet(light, dark);
    assert(css.canFind(":root {\n  --spk-"), css);
    assert(css.canFind("html.dark {\n  --spk-"), css);
    assert(!css.canFind("prefers-color-scheme"), css);
    assert(css.count("--spk-page-bg:") == 2, css);

    const followed = tokenStylesheet(light, dark, TokenSheetOptions(followSystem: true));
    assert(followed.canFind("@media (prefers-color-scheme: dark) {\n  :root {\n    --spk-"), followed);
    assert(followed.count("--spk-page-bg:") == 3, followed);

    assert(!tokenStylesheet(light).canFind("html.dark"));
}

/// The committed site stylesheet is what its theme files emit: a theme edit
/// without a rerun of the generator fails here (`WEB3`, the `THM5` lockstep).
@("web_assets.siteStylesheet.committedSheetIsCurrent")
@system unittest
{
    import std.file : exists, readText;
    import std.path : buildPath, dirName;
    import sparkles.test_runner.skip : skipTest;

    const root = buildPath(__FILE_FULL_PATH__.dirName, "..", "..", "..", "..", "..");
    const committed = buildPath(root, siteStylesheetPath);
    if (!exists(committed))
        skipTest("the docs site is not in this checkout");
    auto fresh = siteStylesheet(root);
    assert(fresh.hasValue, fresh.error.path ~ ": " ~ fresh.error.message);
    assert(fresh.value == readText(committed),
        siteStylesheetPath ~ " is stale: run `dub run --single apps/ci/tools/gen-site-css.d`");
}

/// A callout reads its slot's property, so the token sheet colors it; the
/// fallback keeps a lone document readable.
@("web_assets.markdownPreviewCss.calloutsReadStatusTokens")
@safe unittest
{
    import std.algorithm.searching : canFind;

    assert(markdownPreviewCss.canFind(".callout-note { border-color: var(--spk-status-info-fg, #"));
    assert(markdownPreviewCss.canFind(".callout-caution { border-color: var(--spk-status-error-fg, #"));
    assert(markdownPreviewCss.canFind(".callout-important { border-color: var(--spk-accent-secondary-fg, #"));
}

/// The chrome's custom-property name must be the one the fragment writes —
/// they are set in two different modules and only agree by this test.
@("web_assets.chromeCss.matchesTheFragmentProperty")
@safe pure
unittest
{
    import std.algorithm.searching : canFind;
    import sparkles.docs.fragment : FragmentOptions, gutterProperty;

    // `gutterProperty` is `--hue-gutter:` (declaration form); the sheet reads
    // the same name back through `var()`.
    assert(gutterProperty[$ - 1] == ':');
    assert(chromeCss.canFind("var(" ~ gutterProperty[0 .. $ - 1]), chromeCss);
}

version (unittest)
private const(char)[][] lines(string s) @safe pure nothrow
{
    const(char)[][] outp;
    size_t start;
    foreach (i, char c; s)
        if (c == '\n')
        {
            outp ~= s[start .. i];
            start = i + 1;
        }
    if (start < s.length)
        outp ~= s[start .. $];
    return outp;
}
