// Generated by shader-compile from ui's shaders/effects.d (entry point `curvature`).
// Do not edit: change the D source and regenerate; `--verify` guards this file.
#version 330
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

vec4 _44;
vec3 _46;
float _60;
vec2 _77;
vec4 _531;
vec3 _532;
vec2 _533;

uniform float uAmount;
uniform sampler2D texture0;

in vec2 fragTexCoord;
in vec4 fragColor;
layout(location = 0) out vec4 finalColor;

void main()
{
    vec2 _208 = fragTexCoord + vec2(-0.5);
    vec2 _209 = _208 * _208;
    vec2 _214;
    _214.x = uAmount * (_209.x + _209.y);
    vec2 _222;
    _222.x = 1.0 / ((uAmount * 0.25) + 1.0);
    vec2 _225 = (_222.xx * ((fragTexCoord + (_208 * _214.xx)) + vec2(-0.5))) + vec2(0.5);
    float _226 = _225.x;
    vec4 _242;
    if ((_226 < 0.0) || (_226 > 1.0))
    {
        _242 = vec4(0.0);
    }
    else
    {
        float _230 = _225.y;
        bool _233 = (_230 < 0.0) || (_230 > 1.0);
        vec4 _239;
        if (_233)
        {
            _239 = _44;
        }
        else
        {
            _239 = fragColor * texture(texture0, _225);
        }
        if (_233)
        {
            _242 = vec4(0.0);
        }
        else
        {
            _242 = _239;
        }
    }
    finalColor = _242;
}
