// Generated by `nix run .#shader-compile` from libs/ui/shaders/effects.d (entry point `phosphor`).
// Do not edit: change the D source and regenerate; `--verify` guards this file.
#version 100
precision mediump float;
precision highp int;

vec4 _44;
vec3 _46;
float _60;
vec2 _77;
vec4 _531;
vec3 _532;
vec2 _533;

uniform highp sampler2D texture0;

varying highp vec2 fragTexCoord;
varying highp vec4 fragColor;

void main()
{
    highp vec4 _114 = fragColor * texture2D(texture0, fragTexCoord);
    highp vec3 _116 = _114.xyz * vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625);
    highp float _122 = _116.z + (_116.y + _116.x);
    highp vec4 _125;
    _125.x = _122 * 0.300000011920928955078125;
    _125.y = _122;
    _125.z = _122 * 0.449999988079071044921875;
    gl_FragData[0] = vec4(_125.x, _125.y, _125.z, _114.w);
}
