// Generated by shader-compile from ui's shaders/effects.d (entry point `scanlines`).
// Do not edit: change the D source and regenerate; `--verify` guards this file.
#version 100
precision mediump float;
precision highp int;

vec4 _44;
vec3 _46;
float _60;
vec2 _77;
vec4 _531;
vec3 _532;
vec2 _533;

uniform highp vec2 uExtentCells;
uniform highp sampler2D texture0;

varying highp vec2 fragTexCoord;
varying highp vec4 fragColor;

void main()
{
    highp vec4 _90 = fragColor * texture2D(texture0, fragTexCoord);
    highp vec2 _92 = floor(fragTexCoord * uExtentCells);
    highp vec3 _94 = _90.xyz;
    highp float _95 = _92.y;
    highp vec3 _102 = (!((_95 - (floor(_95 * 0.5) * 2.0)) >= 1.0)) ? _94 : (_94 * vec3(0.62000000476837158203125));
    gl_FragData[0] = vec4(_102.x, _102.y, _102.z, _90.w);
}
