// Generated by `nix run .#shader-compile` from libs/ui/shaders/effects.d (entry point `scanlines`).
// Do not edit: change the D source and regenerate; `--verify` guards this file.
#version 330
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

vec4 _44;
vec3 _46;
float _60;
vec2 _77;
vec4 _531;
vec3 _532;
vec2 _533;

uniform vec2 uExtentCells;
uniform sampler2D texture0;

in vec2 fragTexCoord;
in vec4 fragColor;
layout(location = 0) out vec4 finalColor;

void main()
{
    vec4 _90 = fragColor * texture(texture0, fragTexCoord);
    vec2 _92 = floor(fragTexCoord * uExtentCells);
    vec3 _94 = _90.xyz;
    float _95 = _92.y;
    vec3 _102 = (!((_95 - (floor(_95 * 0.5) * 2.0)) >= 1.0)) ? _94 : (_94 * vec3(0.62000000476837158203125));
    finalColor = vec4(_102.x, _102.y, _102.z, _90.w);
}
