// Generated by shader-compile from ui's shaders/effects.d (entry point `spectrum`).
// Do not edit: change the D source and regenerate; `--verify` guards this file.
#version 330
#ifdef GL_ARB_shading_language_420pack
#extension GL_ARB_shading_language_420pack : require
#endif

vec4 _44;
vec3 _46;
float _60;
vec2 _77;
vec4 _531;
vec3 _532;
vec2 _533;

uniform vec2 uExtentCells;
uniform sampler2D texture0;

in vec2 fragTexCoord;
in vec4 fragColor;
layout(location = 0) out vec4 finalColor;

void main()
{
    vec4 _151 = fragColor * texture(texture0, fragTexCoord);
    vec3 _162;
    _162.x = (floor(floor(fragTexCoord * uExtentCells).x) / ((uExtentCells.x > 1.0) ? uExtentCells.x : 1.0)) * 6.0;
    vec3 _164 = _162.xxx + vec3(0.0, 4.0, 2.0);
    vec3 _171 = abs((_164 - (floor(_164 * vec3(0.16666667163372039794921875)) * vec3(6.0))) + vec3(-3.0)) + vec3(-1.0);
    float _172 = _171.x;
    float _174 = (_172 > 0.0) ? _172 : 0.0;
    float _175 = _171.y;
    float _177 = (_175 > 0.0) ? _175 : 0.0;
    float _178 = _171.z;
    float _180 = (_178 > 0.0) ? _178 : 0.0;
    vec3 _190 = _151.xyz * vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625);
    vec3 _197;
    _197.x = _190.z + (_190.y + _190.x);
    vec3 _199 = _197.xxx * vec3((_174 < 1.0) ? _174 : 1.0, (_177 < 1.0) ? _177 : 1.0, (_180 < 1.0) ? _180 : 1.0);
    finalColor = vec4(_199.x, _199.y, _199.z, _151.w);
}
