// Generated by shader-compile from ui's shaders/effects.d (entry point `spectrum`).
// Do not edit: change the D source and regenerate; `--verify` guards this file.
#version 100
precision mediump float;
precision highp int;

vec4 _44;
vec3 _46;
float _60;
vec2 _77;
vec4 _531;
vec3 _532;
vec2 _533;

uniform highp vec2 uExtentCells;
uniform highp sampler2D texture0;

varying highp vec2 fragTexCoord;
varying highp vec4 fragColor;

void main()
{
    highp vec4 _151 = fragColor * texture2D(texture0, fragTexCoord);
    highp vec3 _162;
    _162.x = (floor(floor(fragTexCoord * uExtentCells).x) / ((uExtentCells.x > 1.0) ? uExtentCells.x : 1.0)) * 6.0;
    highp vec3 _164 = _162.xxx + vec3(0.0, 4.0, 2.0);
    highp vec3 _171 = abs((_164 - (floor(_164 * vec3(0.16666667163372039794921875)) * vec3(6.0))) + vec3(-3.0)) + vec3(-1.0);
    highp float _172 = _171.x;
    highp float _174 = (_172 > 0.0) ? _172 : 0.0;
    highp float _175 = _171.y;
    highp float _177 = (_175 > 0.0) ? _175 : 0.0;
    highp float _178 = _171.z;
    highp float _180 = (_178 > 0.0) ? _178 : 0.0;
    highp vec3 _190 = _151.xyz * vec3(0.2989999949932098388671875, 0.58700001239776611328125, 0.114000000059604644775390625);
    highp vec3 _197;
    _197.x = _190.z + (_190.y + _190.x);
    highp vec3 _199 = _197.xxx * vec3((_174 < 1.0) ? _174 : 1.0, (_177 < 1.0) ? _177 : 1.0, (_180 < 1.0) ? _180 : 1.0);
    gl_FragData[0] = vec4(_199.x, _199.y, _199.z, _151.w);
}
