/**
 * Shared configuration for the conformance layers.
 *
 * `pinnedUnicodeVersion` is kept matched to the width tables generated by
 * `libs/base/tools/gen_unicode_tables.d` (and to the toolchain's `std.uni`
 * grapheme tables). The two-version split (`widthVersion` vs `segVersion`)
 * exists because width is pinned to a fixed UCD release while segmentation
 * rides whatever Phobos `std.uni` ships — they can legitimately differ.
 */
module sparkles.text_conformance.config;

/// Default Unicode version. Keep matched to `gen_unicode_tables.d`'s pin.
enum string pinnedUnicodeVersion = "17.0.0";

/// Resolved run configuration handed to each layer.
struct Config
{
    /// Which layers to run (true = run).
    bool[4] layers = [true, true, true, true];

    /// Offline UCD directory (`--ucd-dir`); empty means download + cache.
    string ucdDir;

    /// Never hit the network; fail on a cache miss.
    bool noNetwork;

    /// Unicode version for the Layer-1 width oracle's UCD inputs.
    string widthVersion = pinnedUnicodeVersion;

    /// Unicode version for the Layer-0/2 grapheme corpora.
    string segVersion = pinnedUnicodeVersion;

    /// Fail rather than skip when the kitty oracle is unavailable.
    bool requireKitty;

    /// Path to the known-divergence allowlist ledger.
    string allowlistPath;

    /// Regenerate the allowlist from this run's divergences.
    bool updateAllowlist;
}
