/**
 * Shared configuration for the conformance layers.
 *
 * `pinnedUnicodeVersion` is kept matched to the width tables generated by
 * `libs/base/tools/gen_unicode_tables.d` (and to the toolchain's `std.uni`
 * grapheme tables). The two-version split (`widthVersion` vs `segVersion`)
 * exists because width is pinned to a fixed UCD release while segmentation
 * rides whatever Phobos `std.uni` ships — they can legitimately differ.
 */
module sparkles.text_conformance.config;

/// Default Unicode version for the **width** tables. Keep matched to
/// `gen_unicode_tables.d`'s pin.
enum string pinnedUnicodeVersion = "17.0.0";

/// Default Unicode version for **segmentation** (Layer 0/2 corpora). This must
/// match the toolchain's Phobos `std.uni` grapheme tables, which lag the width
/// pin: empirically, the current LDC/Phobos segments per Unicode 15.0
/// (`text-conformance --layers 0 --segmentation-unicode-version <v>` reports
/// zero divergences at 15.0.0 and a cluster of Indic-conjunct/emoji-ZWJ
/// divergences at 15.1+). Bump this when you upgrade the compiler and re-run
/// Layer 0 to find the new matching version.
enum string phobosGraphemeUnicodeVersion = "15.0.0";

/// Resolved run configuration handed to each layer.
struct Config
{
    /// Which layers to run (true = run). Index = layer number (0..4).
    bool[5] layers = [true, true, true, true, true];

    /// Offline UCD directory (`--ucd-dir`); empty means download + cache.
    string ucdDir;

    /// Never hit the network; fail on a cache miss.
    bool noNetwork;

    /// Unicode version for the Layer-1 width oracle's UCD inputs.
    string widthVersion = pinnedUnicodeVersion;

    /// Unicode version for the Layer-0/2 grapheme corpora.
    string segVersion = phobosGraphemeUnicodeVersion;

    /// Fail rather than skip when the kitty oracle is unavailable.
    bool requireKitty;

    /// Path to the known-divergence allowlist ledger.
    string allowlistPath;

    /// Regenerate the allowlist from this run's divergences.
    bool updateAllowlist;
}
