#!/usr/bin/env dub
/+ dub.sdl:
    name "wsi_input_echo"
    dependency "sparkles:wsi" path="../../.."
    dependency "sparkles:dql" path="../../.."
    dependency "sparkles:event-horizon" path="../../.."
    dependency "sparkles:core-cli" path="../../.."
    dependency "sparkles:base" path="../../.."
    dependency "sparkles:wired" path="../../.."
    dependency "expected" version="~>0.4.1"
    targetPath "build"
    buildType "checked" {
        buildOptions "optimize" "inline" "debugInfo"
    }
+/
// ci: run --help
/**
Interactive `sparkles:wsi` event echo — the UAT program for the native
window stack. Opens one window on the platform's native backend (Wayland
when `$WAYLAND_DISPLAY` is set, X11 otherwise, AppKit on macOS) and logs
every event the backend queues.

Things to try:
$(LIST
    * hold a key — `repeat` actions (client-synthesized on Wayland);
    * type through your IME — `TextCommitted` and `Composition` lines
        (text-input-v3 on a v3 compositor such as Mutter; XIM through
        `$XMODIFIERS` on X11; `NSTextInputClient` on macOS);
    * scroll, click, and drag — pointer and scroll lines with the shared
        sign convention;
    * drag near a window edge on Wayland — the compositor takes over as an
        interactive resize (GNOME draws no server decorations, so this is
        the only way a bare toplevel resizes there); hold Alt and drag
        anywhere to move the window;
    * press `c` to cycle the standard cursor shapes, `m` to toggle
        maximize, `q` to quit;
    * filter events with `-F "!pointer"`, `-F "pointer.phase == pressed"`, or
        `-F ?` for the schema-generated path and category tables.
)
*/
module wsi_input_echo;

import core.lifetime : move;
import core.time : Duration, msecs;
import std.stdio : writeln;
import std.traits : EnumMembers;

import expected : Expected, err, ok;

import sparkles.base.logger : LogLevel, error, info, initLogger, trace, warning;
import sparkles.base.prettyprint : PrettyPrintOptions, prettyPrint;
import sparkles.core_cli.args;
import sparkles.dql : DqlEngine, DqlFilter, DqlSchema, evalDql, parseDql,
    printDqlHelp;
import sparkles.event_horizon.loop : DefaultLoop, LoopConfig;
import sparkles.input.events : KeyAction, PointerButton;
import sparkles.input.pointer : PointerShape;
import sparkles.wired : CaseStyle, WireCase;
import sparkles.wsi;

/// How close to a border a press must land to count as a resize grip.
private enum double gripSize = 16;

@WireCase(CaseStyle.kebabCase)
enum BackendKind
{
    auto_,
    wayland,
    x11,
    appkit,
}

/// The filtering schema over the WSI event vocabulary, generated by the
/// reflection kernel — the example writes no paths of its own, so `-F ?`
/// can never drift from what the backends actually queue.
alias EventSchema = DqlSchema!WindowEvent;

/// A compiled `-F` filter and the engine that evaluates it; inactive when
/// no filter was given, so every event is logged.
private struct EventFilter
{
    DqlEngine engine;
    DqlFilter filter;
    bool active;

    bool matches(in WindowEvent event)
        => !active || evalDql!EventSchema(engine, filter, event);
}

int main(string[] args) => runCli!WsiInputEcho(args);

@(Command("wsi-input-echo",
    shortDescription: "Interactive native WSI event echo and input test harness",
    description: "Opens a native window on Wayland, X11, or AppKit and logs queued WSI events.",
))
struct WsiInputEcho
{
    @(Option(`W|width`, description: "Window width in logical units"))
    int width = 720;

    @(Option(`H|height`, description: "Window height in logical units"))
    int height = 420;

    @(Option(`f|frames`,
        description: "Process N loop ticks then exit (0 = run until the window closes)"))
    int frames;

    @(Option("backend", description: "Native WSI backend (auto / wayland / x11 / appkit)"))
    BackendKind backend = BackendKind.auto_;

    @(Option(`F|event-filter`,
        description: "DQL event filter, or '?' for the generated schema (e.g. '!pointer', 'keyboard || textCommitted', 'pointer.phase == pressed')"))
    string eventFilter;

    @(Option("no-color", description: "Disable colored output"))
    bool noColor;

    @(Option("trace", description: "Enable trace-level logging"))
    bool trace;

    Expected!(void, string) run() @system
    {
        initLogger(trace ? LogLevel.trace : LogLevel.info);

        EventFilter filter;
        if (eventFilter.length)
        {
            if (eventFilter == "?" || eventFilter == "help")
            {
                printDqlHelp!EventSchema("wsi-input-echo", !noColor);
                return ok();
            }
            auto compiled = parseDql!EventSchema(filter.engine, eventFilter);
            if (compiled.hasError)
                return err!void("event filter error: " ~ compiled.error.message);
            filter.filter = compiled.value.move;
            filter.active = true;
        }

        auto opt = PrettyPrintOptions!void(
            colored: !noColor,
            softMaxWidth: 100,
        );

        DefaultLoop loop;
        auto loopCreated = DefaultLoop.create(loop, LoopConfig());
        if (loopCreated.hasError)
            return err!void("failed to create Event Horizon loop");

        version (OSX)
        {
            if (backend != BackendKind.auto_ && backend != BackendKind.appkit)
                return err!void("requested backend is not available on macOS");

            AppKitWsi wsi;
            auto opened = AppKitWsi.open(wsi);
            if (opened.hasError)
            {
                if (opened.error.kind == WsiErrorKind.unavailable)
                    return skip("AppKit unavailable", cast(string) opened.error.diagnostic[]);
                return err!void("AppKit open failed: " ~ cast(string) opened.error.diagnostic[]);
            }
            auto report = runBackend(wsi, loop, "AppKit", this, filter);
            if (report.hasError)
                return err!void(report.error);
            writeln(prettyPrint(report.value, opt));
            return ok();
        }
        else version (linux)
        {
            import core.stdc.stdlib : getenv;

            bool useWayland;
            final switch (backend)
            {
            case BackendKind.auto_:
                useWayland = getenv("WAYLAND_DISPLAY") !is null;
                break;
            case BackendKind.wayland:
                useWayland = true;
                break;
            case BackendKind.x11:
                useWayland = false;
                break;
            case BackendKind.appkit:
                return err!void("AppKit backend is only available on macOS");
            }

            if (useWayland)
            {
                WaylandWsi wsi;
                auto opened = WaylandWsi.open(wsi, loop);
                if (opened.hasError)
                {
                    if (opened.error.kind == WsiErrorKind.unavailable)
                        return skip("Wayland unavailable", cast(string) opened.error.diagnostic[]);
                    return err!void("Wayland open failed: " ~ cast(string) opened.error.diagnostic[]);
                }
                while (!wsi.bootstrapComplete)
                {
                    auto ticked = wsi.runIntegratedOnce(loop, 100.msecs);
                    if (ticked.hasError)
                        return err!void("Wayland bootstrap failed");
                }
                auto report = runBackend(wsi, loop, "Wayland", this, filter);
                if (report.hasError)
                    return err!void(report.error);
                writeln(prettyPrint(report.value, opt));
                return ok();
            }
            else
            {
                X11Wsi wsi;
                auto opened = X11Wsi.open(wsi);
                if (opened.hasError)
                {
                    if (opened.error.kind == WsiErrorKind.unavailable)
                        return skip("X11 unavailable", cast(string) opened.error.diagnostic[]);
                    return err!void("X11 open failed: " ~ cast(string) opened.error.diagnostic[]);
                }
                auto attached = wsi.attach(loop);
                if (attached.hasError)
                    return err!void("X11 attach failed: " ~ cast(string) attached.error.diagnostic[]);
                auto report = runBackend(wsi, loop, "X11", this, filter);
                if (report.hasError)
                    return err!void(report.error);
                writeln(prettyPrint(report.value, opt));
                return ok();
            }
        }
        else
        {
            return skip("no native backend for this platform yet");
        }
    }
}

/// A skip is a success: the environment lacks a display or a driver.
Expected!(void, string) skip(string what, string detail = null)
{
    if (detail.length)
        writeln("SKIP: ", what, " — ", detail);
    else
        writeln("SKIP: ", what);
    return ok();
}

/// What the run actually did, so an invocation is verifiable.
struct RunReport
{
    string backend;
    uint eventsReceived;
    uint eventsLogged;
    uint readyEvents;
    uint metricsEvents;
    uint keyEvents;
    uint textEvents;
    uint compositionEvents;
    uint pointerEvents;
    uint scrollEvents;
    uint focusEvents;
    uint repaints;
    string exitedBecause;
}

private struct EchoState
{
    WindowId id;
    SurfaceMetrics metrics;
    size_t cursorIndex;
    bool repaint;
    bool quit;
}

private Expected!(void, string) echoLoop(Backend)(ref Backend wsi, ref DefaultLoop loop,
    ref EchoState state, ref RunReport report, int frameBudget,
    ref EventFilter filter, in PrettyPrintOptions!void opt)
{
    void handle(WindowEvent event)
    {
        report.eventsReceived++;

        if (!filter.matches(event))
            return;

        report.eventsLogged++;
        event.payload.match!(
            (in ReadyEvent value) {
                state.metrics = value.metrics;
                state.repaint = true;
                report.readyEvents++;
                info(i"#$(event.sequence) ready $(prettyPrint(value, opt))");
            },
            (in SurfaceMetricsChangedEvent value) {
                state.metrics = value.metrics;
                state.repaint = true;
                report.metricsEvents++;
                info(i"#$(event.sequence) metrics $(prettyPrint(value, opt))");
            },
            (in KeyboardEvent value) {
                report.keyEvents++;
                info(i"#$(event.sequence) key $(prettyPrint(value, opt))");
                if (value.action != KeyAction.release)
                    return;
                if (value.logical.kind == LogicalKeyKind.character)
                    handleCommand(wsi, state, value.logical.character, opt);
            },
            (in TextCommittedEvent value) {
                report.textEvents++;
                info(i"#$(event.sequence) text $(prettyPrint(value, opt))");
            },
            (in CompositionEvent value) {
                report.compositionEvents++;
                info(i"#$(event.sequence) composition $(prettyPrint(value, opt))");
            },
            (in PointerEvent value) {
                report.pointerEvents++;
                info(i"#$(event.sequence) pointer $(prettyPrint(value, opt))");
                if (value.phase == PointerPhase.pressed
                    && value.button == PointerButton.left)
                    handleLeftPress(wsi, state, value);
            },
            (in ScrollEvent value) {
                report.scrollEvents++;
                info(i"#$(event.sequence) scroll $(prettyPrint(value, opt))");
            },
            (in FocusChangedEvent value) {
                report.focusEvents++;
                info(i"#$(event.sequence) focus $(prettyPrint(value, opt))");
            },
            (in CloseRequestedEvent _) {
                info(i"#$(event.sequence) close requested — quitting");
                state.quit = true;
                report.exitedBecause = "window closed";
            },
            (in DestroyedEvent _) {
                info(i"#$(event.sequence) destroyed");
                state.quit = true;
                report.exitedBecause = "destroyed";
            },
            (other) {
                info(i"#$(event.sequence) $(typeof(other).stringof)");
            });
    }

    WindowEvent[128] batch;
    size_t batched;
    int loopsRun;
    while (!state.quit && (frameBudget == 0 || loopsRun < frameBudget))
    {
        loopsRun++;
        static if (is(typeof(wsi.runIntegratedOnce(loop, Duration.init))))
            auto ticked = wsi.runIntegratedOnce(loop, 250.msecs);
        else
            auto ticked = loop.runHostedOnce(wsi, 250.msecs);
        if (ticked.hasError)
        {
            error(i"loop error: $(ticked.error.context) (errno=$(ticked.error.errnoValue) stage=$(ticked.error.stage))");
            auto sticky = wsi.drain((WindowEvent _) @safe {});
            if (sticky.hasError)
                error(i"backend diagnostic: $(sticky.error.diagnostic[]) (kind=$(sticky.error.kind) native=$(sticky.error.nativeCode))");
            return err!void("loop error");
        }
        batched = 0;
        auto drained = wsi.drain((WindowEvent event) @safe {
            if (batched < batch.length)
                () @trusted { batch[batched++] = event; }();
        });
        if (drained.hasError)
        {
            error(i"event queue error: $(drained.error.diagnostic[])");
            return err!void(cast(string) drained.error.diagnostic[]);
        }
        foreach (ref event; batch[0 .. batched])
            handle(event);
        if (state.repaint)
        {
            state.repaint = false;
            report.repaints++;
            paintIfNeeded(wsi, state);
        }
    }
    if (frameBudget > 0 && loopsRun >= frameBudget && !state.quit)
        report.exitedBecause = "frame budget reached";
    return ok();
}

private void handleCommand(Backend)(ref Backend wsi, ref EchoState state,
    dchar command, in PrettyPrintOptions!void opt)
{
    switch (command)
    {
        case 'q':
            info(i"command: quit");
            state.quit = true;
            break;
        case 'c':
            static immutable shapes = [EnumMembers!PointerShape];
            state.cursorIndex = (state.cursorIndex + 1) % shapes.length;
            const shape = shapes[state.cursorIndex];
            auto set = wsi.setCursor(state.id, shape);
            if (set.hasError)
                warning(i"setCursor($(shape)): $(set.error.diagnostic[])");
            else
                info(i"setCursor($(shape)): ok");
            break;
        case 'm':
            static if (is(typeof(wsi.setMaximized(state.id, true))))
            {
                static bool maximized;
                maximized = !maximized;
                auto result = wsi.setMaximized(state.id, maximized);
                if (result.hasError)
                    warning(i"setMaximized($(maximized)): $(result.error.diagnostic[])");
                else
                    info(i"setMaximized($(maximized)): ok");
            }
            else
                info(i"setMaximized: not available on this backend");
            break;
        default:
            break;
    }
}

private void handleLeftPress(Backend)(ref Backend wsi, ref EchoState state,
    in PointerEvent value)
{
    static if (is(typeof(wsi.startInteractiveResize(state.id,
        ResizeEdge.none))))
    {
        if (value.modifiers.alt)
        {
            auto moved = wsi.startInteractiveMove(state.id);
            if (moved.hasError)
                warning(i"startInteractiveMove: $(moved.error.diagnostic[])");
            else
                info(i"startInteractiveMove: ok");
            return;
        }
        const edge = resizeEdgeAt(state.metrics, value.logicalPosition.x,
            value.logicalPosition.y);
        if (edge == ResizeEdge.none)
            return;
        auto resized = wsi.startInteractiveResize(state.id, edge);
        if (resized.hasError)
            warning(i"startInteractiveResize($(edge)): $(resized.error.diagnostic[])");
        else
            info(i"startInteractiveResize($(edge)): ok");
    }
}

// Painting exists only where an unmapped surface would stay invisible:
// a Wayland toplevel maps when a buffer is committed, while X11 windows
// paint their background pixel and AppKit windows draw their own chrome.
version (linux)
{
    import core.sys.posix.stdlib : mkstemp;
    import core.sys.posix.unistd : posixClose = close, ftruncate, unlink;

    import wayland_native;

    private struct ShmGlobal
    {
        wl_shm* shm;
    }

    private extern (C) void onShmGlobal(void* data, wl_registry* registry,
        uint name, const(char)* interfaceName, uint) nothrow @nogc
    {
        import core.stdc.string : strcmp;

        auto probe = cast(ShmGlobal*) data;
        if (strcmp(interfaceName, wl_shm_interface.name) == 0
            && probe.shm is null)
            probe.shm = cast(wl_shm*) wl_registry_bind(registry, name,
                &wl_shm_interface, 1);
    }

    private extern (C) void onShmGlobalRemove(void*, wl_registry*, uint)
        nothrow @nogc
    {
    }

    private immutable wl_registry_listener shmListener = {
        &onShmGlobal, &onShmGlobalRemove
    };

    /*
    Fills the surface with a flat color and brighter `gripSize` borders —
    the visible affordance for the compositor-resize zones. One buffer per
    paint; the previous one is destroyed on the next call, when the
    compositor has long since attached its replacement.
    */
    private struct WaylandPainter
    {
        wl_shm* shm;
        wl_buffer* previous;

        bool bind(wl_display* display)
        {
            ShmGlobal probe;
            auto registry = wl_display_get_registry(display);
            if (registry is null)
                return false;
            scope (exit) wl_proxy_destroy(cast(wl_proxy*) registry);
            if (wl_registry_add_listener(registry,
                    cast(wl_registry_listener*) &shmListener, &probe) != 0
                || wl_display_roundtrip(display) < 0)
                return false;
            shm = probe.shm;
            return shm !is null;
        }

        bool paint(wl_display* display, wl_surface* surface, int width,
            int height)
        {
            import core.sys.posix.sys.mman : MAP_FAILED, MAP_SHARED,
                PROT_READ, PROT_WRITE, mmap, munmap;

            if (shm is null || width <= 0 || height <= 0)
                return false;
            char[26] path = "/tmp/wsi-echo-shm-XXXXXX\0\0";
            const fd = mkstemp(path.ptr);
            if (fd < 0)
                return false;
            scope (exit) posixClose(fd);
            unlink(path.ptr);
            const stride = width * 4;
            const size = stride * height;
            if (ftruncate(fd, size) != 0)
                return false;
            auto pixels = mmap(null, size, PROT_READ | PROT_WRITE,
                MAP_SHARED, fd, 0);
            if (pixels is MAP_FAILED)
                return false;
            auto view = (cast(uint*) pixels)[0 .. width * height];
            foreach (y; 0 .. height)
                foreach (x; 0 .. width)
                {
                    const grip = x < gripSize || y < gripSize
                        || x >= width - gripSize || y >= height - gripSize;
                    view[y * width + x] = grip ? 0xFF3A6EA5 : 0xFF20242C;
                }
            munmap(pixels, size);

            auto pool = wl_shm_create_pool(shm, fd, size);
            if (pool is null)
                return false;
            scope (exit) wl_shm_pool_destroy(pool);
            auto buffer = wl_shm_pool_create_buffer(pool, 0, width, height,
                stride, WL_SHM_FORMAT_XRGB8888);
            if (buffer is null)
                return false;
            wl_surface_attach(surface, buffer, 0, 0);
            wl_surface_damage(surface, 0, 0, width, height);
            wl_surface_commit(surface);
            if (previous !is null)
                wl_buffer_destroy(previous);
            previous = buffer;
            return wl_display_flush(display) >= 0;
        }
    }

    private WaylandPainter painter;

    private void paintIfNeeded(Backend)(ref Backend wsi, ref EchoState state)
    {
        static if (is(Backend == WaylandWsi))
        {
            if (state.metrics.suspended)
                return;
            auto queried = wsi.nativeHandles(state.id);
            if (queried.hasError)
                return;
            auto handles = queried.value;
            auto display = handles.display.match!(
                (in WaylandDisplayHandle handle)
                    => cast(wl_display*) handle.display,
                (_) => null);
            auto surface = handles.window.match!(
                (in WaylandWindowHandle handle)
                    => cast(wl_surface*) handle.surface,
                (_) => null);
            if (display is null || surface is null)
                return;
            assert(!wsi.beginNativeIo().hasError);
            scope (exit) assert(!wsi.endNativeIo().hasError);
            if (painter.shm is null && !painter.bind(display))
                return;
            painter.paint(display, surface,
                cast(int) state.metrics.logicalSize.width,
                cast(int) state.metrics.logicalSize.height);
        }
    }
}
else
{
    private void paintIfNeeded(Backend)(ref Backend, ref EchoState)
    {
    }
}

private Expected!(RunReport, string) runBackend(Backend)(ref Backend wsi, ref DefaultLoop loop,
    string name, in WsiInputEcho options, ref EventFilter filter)
{
    auto opt = PrettyPrintOptions!void(
        colored: !options.noColor,
        softMaxWidth: 100,
    );

    WindowConfig config;
    if (!config.title.assign("sparkles wsi-input-echo"))
        return err!RunReport("failed to set window title");
    config.logicalSize = LogicalSize(options.width, options.height);

    info(i"creating window with config: $(prettyPrint(config, opt))");
    auto created = wsi.createWindow(config);
    if (created.hasError)
        return err!RunReport("createWindow failed: " ~ cast(string) created.error.diagnostic[]);

    EchoState state;
    state.id = created.value;
    RunReport report = {
        backend: name,
        exitedBecause: "window closed",
    };

    info(i"wsi-input-echo on $(name) — hold keys, type through your IME, scroll, drag the blue border to resize, alt+drag to move, c cycles cursors, m toggles maximize, q quits");

    // Drain the ready event before the first paint so metrics are real.
    auto drained = wsi.drain((WindowEvent event) @safe {
        event.payload.match!(
            (in ReadyEvent value) { state.metrics = value.metrics; },
            (_) {});
    });
    if (drained.hasError)
        return err!RunReport("drain error: " ~ cast(string) drained.error.diagnostic[]);

    // On Wayland the ready event follows the first configure, later in the
    // loop; painting waits for real metrics either way.
    if (!state.metrics.suspended)
        paintIfNeeded(wsi, state);

    auto result = echoLoop(wsi, loop, state, report, options.frames, filter, opt);
    if (result.hasError)
        return err!RunReport(result.error);

    return ok(report);
}
