// macOS/AppKit F10 demo — pointer lock / confine / relative motion
// (../../../features/f10-pointer-capture.md).
// The mouselook problem on macOS is assembled from three independent pieces:
// stop the cursor (CGAssociateMouseAndMouseCursorPosition(false)), hide it
// (NSCursor.hide — app-scoped counter — vs CGDisplayHideCursor — per-display),
// and read relative motion (NSEvent.deltaX/deltaY on mouseMoved:, which keeps
// flowing while the cursor is pinned). There is NO public confine-to-rect API;
// this demo implements the warp-back workaround and logs its artifacts.
//
// What it logs (A[ssh]; locked console — no real pointer, so motion is driven by
// synthetic NSEvents dispatched in-process, the f06/f07 route-1 workhorse):
//   - lock enter/exit: CGAssociateMouseAndMouseCursorPosition return value (and
//     the absence of any read-back getter), NSCursor.hide/unhide pairing,
//     saved-position capture + CGWarpMouseCursorPosition restore on exit;
//   - the two ways to build a delta-bearing synthetic mouseMoved:
//       a. +[NSEvent mouseEventWithType:...] — the constructor has NO delta
//          parameters; the wrapped event's deltaX/deltaY are the probe;
//       b. CGEventCreateMouseEvent + CGEventSetIntegerValueField(
//          kCGMouseEventDeltaX/Y) wrapped via +[NSEvent eventWithCGEvent:] —
//          read back at the CG layer, at the wrapped-NSEvent layer, and at the
//          view's mouseMoved: (whatever delta survives each hop is the finding);
//   - CGWarpMouseCursorPosition: CGError + CGEventCreate location read-back
//     (does the warp move the CG-side pointer under a locked session?), whether
//     any mouseMoved is generated by the warp, and the classic suppression
//     interval (CGEventSourceGet/SetLocalEventsSuppressionInterval);
//   - CGDisplayHideCursor/CGDisplayShowCursor returns, contrasted with the
//     app-scoped NSCursor counter;
//   - the confine workaround: a center-half confine rect, scripted motion that
//     leaves it, warp-back + the artifact (the out-of-bounds event is already
//     delivered before the warp can react);
//   - a crosshair/angle readout (yaw/pitch integrated from deltas) drawn in
//     drawRect: (visible pixels are Tier C; the numbers are in the log).
//
// Modes: WSI_AUTO_EXIT=1 = bounded scripted run; without it the window stays up
// and a mouse click toggles mouselook for a manual (Tier C) session.
// Headless-safe: prints `SKIP:` and exits 0 when there is no window server.
module app;

import core.attribute : selector;
import core.stdc.stdio : printf;
import core.stdc.stdlib : getenv;

import instrument : instr, instrInit;
import objc.autorelease : autoreleasepool_push, autoreleasepool_pop; // objective-d
import objc.rt : SEL;

// --- Geometry (NSPoint/NSRect are layout-identical to CGPoint/CGRect) ------------

extern (C) struct NSPoint
{
    double x, y;
}

extern (C) struct NSSize
{
    double width, height;
}

extern (C) struct NSRect
{
    NSPoint origin;
    NSSize size;
}

// --- CoreGraphics C API -----------------------------------------------------------

extern (C) nothrow @nogc
{
    uint CGMainDisplayID();
    NSRect CGDisplayBounds(uint display);

    // The lock trio: dissociate, warp, hide (display-scoped variant).
    int CGAssociateMouseAndMouseCursorPosition(uint connected); // CGError
    int CGWarpMouseCursorPosition(NSPoint newPosition); // CGError
    int CGDisplayHideCursor(uint display); // CGError
    int CGDisplayShowCursor(uint display); // CGError

    // Pointer-position read-back + synthetic mouse events with delta fields.
    void* CGEventCreate(void* source);
    NSPoint CGEventGetLocation(void* event);
    void* CGEventCreateMouseEvent(void* source, uint type, NSPoint pos, uint button);
    void CGEventSetIntegerValueField(void* event, uint field, long value);
    long CGEventGetIntegerValueField(void* event, uint field);

    // The classic warp-suppression-interval knob (per event source).
    void* CGEventSourceCreate(int stateID);
    double CGEventSourceGetLocalEventsSuppressionInterval(void* source);
    void CGEventSourceSetLocalEventsSuppressionInterval(void* source, double seconds);

    void CFRelease(void* obj);

    void CGContextSetRGBFillColor(void* ctx, double r, double g, double b, double a);
    void CGContextFillRect(void* ctx, NSRect rect);
}

enum uint kCGEventMouseMoved = 5; // CGEventType
enum uint kCGMouseEventDeltaX = 4; // CGEventField
enum uint kCGMouseEventDeltaY = 5;
enum int kCGEventSourceStateCombinedSessionState = 0;

// --- AppKit class declarations ----------------------------------------------------

extern (Objective-C):

extern class NSObject
{
}

extern class NSString : NSObject
{
    static NSString alloc() @selector("alloc");
    NSString initWithUTF8String(const(char)* s) @selector("initWithUTF8String:");
}

extern class NSEvent : NSObject
{
    static NSEvent mouseEventWithType(long type, NSPoint location, ulong modifierFlags,
        double timestamp, long windowNumber, NSObject context, long eventNumber,
        long clickCount, double pressure)
        @selector("mouseEventWithType:location:modifierFlags:timestamp:windowNumber:context:eventNumber:clickCount:pressure:");
    static NSEvent eventWithCGEvent(void* cgEvent) @selector("eventWithCGEvent:");
    static NSEvent otherEventWithType(long type, NSPoint location, ulong modifierFlags,
        double timestamp, long windowNumber, NSObject context, short subtype,
        long data1, long data2)
        @selector("otherEventWithType:location:modifierFlags:timestamp:windowNumber:context:subtype:data1:data2:");
    static NSPoint mouseLocation() @selector("mouseLocation");
    long type() @selector("type");
    NSPoint locationInWindow() @selector("locationInWindow");
    double deltaX() @selector("deltaX");
    double deltaY() @selector("deltaY");
    long windowNumber() @selector("windowNumber");
    NSObject window() @selector("window");
}

extern class NSCursor : NSObject
{
    static void hide() @selector("hide");
    static void unhide() @selector("unhide");
}

extern class NSTimer : NSObject
{
    static NSTimer scheduledTimerWithTimeInterval(double interval, NSObject target,
        SEL sel, NSObject userInfo, bool repeats)
        @selector("scheduledTimerWithTimeInterval:target:selector:userInfo:repeats:");
}

extern class NSApplication : NSObject
{
    static NSApplication sharedApplication() @selector("sharedApplication");
    void setActivationPolicy(long policy) @selector("setActivationPolicy:");
    void activateIgnoringOtherApps(bool flag) @selector("activateIgnoringOtherApps:");
    void run() @selector("run");
    void stop(NSObject sender) @selector("stop:");
    void postEvent(NSEvent event, bool atStart) @selector("postEvent:atStart:");
}

extern class NSGraphicsContext : NSObject
{
    static NSGraphicsContext currentContext() @selector("currentContext");
    void* CGContext() @selector("CGContext");
}

extern class NSView : NSObject
{
    bool acceptsFirstResponder() @selector("acceptsFirstResponder");
    NSRect bounds() @selector("bounds");
    void setNeedsDisplay(bool flag) @selector("setNeedsDisplay:");
}

extern class NSWindow : NSObject
{
    static NSWindow alloc() @selector("alloc");
    NSWindow initWithContentRect(NSRect contentRect, ulong styleMask,
        ulong backing, bool defer) @selector("initWithContentRect:styleMask:backing:defer:");
    void setTitle(NSString title) @selector("setTitle:");
    void setContentView(NSObject view) @selector("setContentView:");
    void makeKeyAndOrderFront(NSObject sender) @selector("makeKeyAndOrderFront:");
    bool makeFirstResponder(NSObject responder) @selector("makeFirstResponder:");
    void sendEvent(NSEvent event) @selector("sendEvent:");
    long windowNumber() @selector("windowNumber");
    NSRect frame() @selector("frame");
    NSRect convertRectToScreen(NSRect r) @selector("convertRectToScreen:");
    bool acceptsMouseMovedEvents() @selector("acceptsMouseMovedEvents");
    void setAcceptsMouseMovedEvents(bool flag) @selector("setAcceptsMouseMovedEvents:");
}

// The mouselook view: logs abs+rel motion, integrates a yaw/pitch readout, and
// enforces the confine rect (warp-back workaround) while it is active.
class LookView : NSView
{
    static LookView alloc() @selector("alloc");
    LookView initWithFrame(NSRect frame) @selector("initWithFrame:");

    override bool acceptsFirstResponder() @selector("acceptsFirstResponder")
    {
        return true;
    }

    void drawRect(NSRect dirtyRect) @selector("drawRect:")
    {
        // Tier-C visual aid: dark field, confine region, crosshair at yaw/pitch.
        void* ctx = NSGraphicsContext.currentContext().CGContext();
        immutable b = this.bounds();
        CGContextSetRGBFillColor(ctx, 0.12, 0.12, 0.14, 1);
        CGContextFillRect(ctx, b);
        if (g_confine)
        {
            CGContextSetRGBFillColor(ctx, 0.18, 0.22, 0.18, 1);
            CGContextFillRect(ctx, confineRectView(b));
        }
        immutable cx = b.size.width / 2 + clampd(g_yaw, -100, 100);
        immutable cy = b.size.height / 2 - clampd(g_pitch, -100, 100);
        CGContextSetRGBFillColor(ctx, 0.9, 0.3, 0.2, 1);
        CGContextFillRect(ctx, NSRect(NSPoint(cx - 12, cy - 1), NSSize(24, 2)));
        CGContextFillRect(ctx, NSRect(NSPoint(cx - 1, cy - 12), NSSize(2, 24)));
    }

    void mouseMoved(NSEvent e) @selector("mouseMoved:")
    {
        onMotion(e, "mouseMoved");
    }

    void mouseDragged(NSEvent e) @selector("mouseDragged:")
    {
        onMotion(e, "mouseDragged");
    }

    void mouseDown(NSEvent e) @selector("mouseDown:")
    {
        // Interactive (Tier C) toggle: click = mouselook on/off.
        instr("mouse_down", "lock_toggle=%d", g_lock ? 0 : 1);
        if (!g_auto)
            g_lock ? exitLock() : enterLock();
    }

    void tick(NSTimer t) @selector("tick:")
    {
        onStep();
    }
}

extern (D): // back to D linkage

enum NSApplicationActivationPolicyRegular = 0;
enum : ulong
{
    NSWindowStyleMaskTitled = 1,
    NSWindowStyleMaskClosable = 2,
    NSWindowStyleMaskResizable = 8,
}

enum ulong NSBackingStoreBuffered = 2;
enum long NSEventTypeMouseMoved = 5;
enum long NSEventTypeApplicationDefined = 15;

// --- Demo state -------------------------------------------------------------------

__gshared NSApplication g_app;
__gshared NSWindow g_win;
__gshared LookView g_view;
__gshared long g_winNum;
__gshared bool g_auto;
__gshared int g_step;

__gshared bool g_lock; // mouselook active
__gshared NSPoint g_savedCG; // CG-coord pointer position captured at lock enter
__gshared double g_yaw = 0, g_pitch = 0; // crosshair readout, degrees-ish
__gshared bool g_confine; // confine workaround active
__gshared NSRect g_confineScreen; // confine rect in AppKit screen coords (y-up)
__gshared int g_arrivals; // mouseMoved/mouseDragged deliveries
__gshared int g_arrivalsAtWarp; // snapshot to detect warp-generated events
__gshared int g_warps; // confine warp-backs issued
__gshared int g_outOfBounds; // events delivered outside the confine rect
__gshared const(char)* g_route = "none"; // current injection route label

double clampd(double v, double lo, double hi) nothrow @nogc
{
    return v < lo ? lo : (v > hi ? hi : v);
}

// --- Coordinate helpers -----------------------------------------------------------
// AppKit screen coords are bottom-left-origin y-up; CG global coords are
// top-left-origin y-down. Flip via the main display height (single-display box).

NSPoint screenToCG(NSPoint p)
{
    immutable db = CGDisplayBounds(CGMainDisplayID());
    return NSPoint(p.x, db.size.height - p.y);
}

NSPoint cgPointerLocation()
{
    void* ev = CGEventCreate(null);
    immutable p = CGEventGetLocation(ev);
    CFRelease(ev);
    return p;
}

// Window-content point -> AppKit screen point (content view origin == window base).
NSPoint viewToScreen(NSPoint p)
{
    return g_win.convertRectToScreen(NSRect(p, NSSize(1, 1))).origin;
}

NSRect confineRectView(NSRect b)
{
    // Center half of the content view.
    return NSRect(NSPoint(b.size.width / 4, b.size.height / 4),
        NSSize(b.size.width / 2, b.size.height / 2));
}

// --- Lock enter/exit ---------------------------------------------------------------

void enterLock()
{
    g_savedCG = cgPointerLocation();
    instr("lock_save", "cg_pos=(%.1f,%.1f)", g_savedCG.x, g_savedCG.y);
    NSCursor.hide();
    instr("cursor", "op=NSCursor_hide scope=app note=balanced_counter");
    immutable err = CGAssociateMouseAndMouseCursorPosition(0);
    g_lock = true;
    // There is no CGGetAssociateMouseAndMouseCursorPosition — the association
    // state is write-only; the app must track it itself.
    instr("lock", "state=on assoc_err=%d readback=no_public_getter", err);
}

void exitLock()
{
    immutable err = CGAssociateMouseAndMouseCursorPosition(1);
    immutable werr = CGWarpMouseCursorPosition(g_savedCG);
    immutable after = cgPointerLocation();
    NSCursor.unhide();
    instr("cursor", "op=NSCursor_unhide scope=app");
    g_lock = false;
    instr("lock", "state=off assoc_err=%d restore_warp_err=%d target=(%.1f,%.1f) readback=(%.1f,%.1f)",
        err, werr, g_savedCG.x, g_savedCG.y, after.x, after.y);
}

// --- Motion handling (the view's mouseMoved/mouseDragged funnel) -------------------

void onMotion(NSEvent e, const(char)* kind)
{
    ++g_arrivals;
    immutable dx = e.deltaX();
    immutable dy = e.deltaY();
    NSPoint p = e.locationInWindow();
    // A window-less event (CGEvent-wrapped) reports locationInWindow in AppKit
    // screen coords already; a window-bound one needs conversion.
    immutable NSPoint sp = e.window() !is null ? viewToScreen(p) : p;
    instr("pointer", "abs x=%.1f y=%.1f screen=(%.1f,%.1f) kind=%s win=%ld",
        p.x, p.y, sp.x, sp.y, kind, e.windowNumber());
    // NSEvent deltas are post-acceleration (WindowServer ballistics) — raw=0.
    // Raw counts would need IOHIDManager, below the window system.
    instr("pointer", "rel dx=%.2f dy=%.2f raw=0 route=%s", dx, dy, g_route);
    if (g_lock)
    {
        g_yaw += dx * 0.5;
        g_pitch += dy * 0.5;
        instr("mouselook", "yaw=%.2f pitch=%.2f", g_yaw, g_pitch);
        g_view.setNeedsDisplay(true);
    }
    if (g_confine)
        enforceConfine(sp);
}

void enforceConfine(NSPoint screenPt)
{
    immutable r = g_confineScreen;
    immutable inX = screenPt.x >= r.origin.x && screenPt.x <= r.origin.x + r.size.width;
    immutable inY = screenPt.y >= r.origin.y && screenPt.y <= r.origin.y + r.size.height;
    if (inX && inY)
        return;
    // The artifact: this event ALREADY arrived at an out-of-bounds position —
    // the warp is reactive, one event too late, every time the pointer leaves.
    ++g_outOfBounds;
    immutable clamped = NSPoint(
        clampd(screenPt.x, r.origin.x, r.origin.x + r.size.width),
        clampd(screenPt.y, r.origin.y, r.origin.y + r.size.height));
    immutable err = CGWarpMouseCursorPosition(screenToCG(clamped));
    ++g_warps;
    instr("confine", "warp from=(%.1f,%.1f) to=(%.1f,%.1f) err=%d note=event_already_delivered_outside",
        screenPt.x, screenPt.y, clamped.x, clamped.y, err);
}

// --- Synthetic motion injection -----------------------------------------------------

// Dispatch in-process: try [window sendEvent:]; if the view never sees it, fall
// back to calling mouseMoved: directly (either outcome is logged).
void dispatchMouse(NSEvent e, const(char)* label)
{
    if (e is null)
    {
        instr("inject", "label=%s result=nil_event", label);
        return;
    }
    immutable before = g_arrivals;
    g_route = "sendEvent";
    g_win.sendEvent(e);
    if (g_arrivals == before)
    {
        instr("route", "label=%s sendEvent=not_delivered fallback=direct", label);
        g_route = "direct";
        g_view.mouseMoved(e);
    }
    else
        instr("route", "label=%s sendEvent=delivered", label);
    g_route = "none";
}

// Probe (a): the plain NSEvent constructor — it has NO delta parameters.
void injectPlainMove(NSPoint viewPt, const(char)* label)
{
    NSEvent e = NSEvent.mouseEventWithType(NSEventTypeMouseMoved, viewPt, 0, 0,
        g_winNum, null, 0, 0, 0);
    instr("inject", "route=nsevent label=%s loc=(%.0f,%.0f) ctor_deltas=none wrapped_dx=%.2f wrapped_dy=%.2f",
        label, viewPt.x, viewPt.y, e.deltaX(), e.deltaY());
    dispatchMouse(e, label);
}

// Probe (b): CGEvent with kCGMouseEventDeltaX/Y set, wrapped via eventWithCGEvent.
void injectCGMove(NSPoint screenPt, long dx, long dy, const(char)* label)
{
    void* cg = CGEventCreateMouseEvent(null, kCGEventMouseMoved, screenToCG(screenPt), 0);
    if (cg is null)
    {
        instr("inject", "route=cgevent_wrap label=%s result=create_failed", label);
        return;
    }
    CGEventSetIntegerValueField(cg, kCGMouseEventDeltaX, dx);
    CGEventSetIntegerValueField(cg, kCGMouseEventDeltaY, dy);
    instr("inject", "route=cgevent_wrap label=%s cg_dx=%ld cg_dy=%ld",
        label, CGEventGetIntegerValueField(cg, kCGMouseEventDeltaX),
        CGEventGetIntegerValueField(cg, kCGMouseEventDeltaY));
    NSEvent e = NSEvent.eventWithCGEvent(cg);
    if (e !is null)
        instr("wrap", "label=%s type=%ld wrapped_dx=%.2f wrapped_dy=%.2f win=%ld",
            label, e.type(), e.deltaX(), e.deltaY(), e.windowNumber());
    dispatchMouse(e, label);
    CFRelease(cg);
}

// --- The scripted run ----------------------------------------------------------------

void stopApp()
{
    instr("step", "name=NSApp_stop");
    g_app.stop(null);
    NSEvent ev = NSEvent.otherEventWithType(NSEventTypeApplicationDefined,
        NSPoint(0, 0), 0, 0, 0, null, 0, 0, 0);
    g_app.postEvent(ev, true); // stop: is only checked after an event dispatch
}

void onStep()
{
    if (!g_auto)
        return;
    immutable b = g_view.bounds();
    immutable center = NSPoint(b.size.width / 2, b.size.height / 2);
    switch (g_step)
    {
    case 0: // Baseline reads: AppKit vs CG pointer position, mouse-moved opt-in.
        {
            immutable nsLoc = NSEvent.mouseLocation();
            immutable cgLoc = cgPointerLocation();
            instr("baseline", "nsevent_mouseLocation=(%.1f,%.1f) cgevent_location=(%.1f,%.1f) accepts_mouse_moved=%d",
                nsLoc.x, nsLoc.y, cgLoc.x, cgLoc.y,
                g_win.acceptsMouseMovedEvents() ? 1 : 0);
        }
        break;
    case 1:
        enterLock();
        break;
    case 2: // (a) plain synthetic mouseMoved: no way to carry a delta.
        injectPlainMove(center, "plain_move_center");
        break;
    case 3: // (b) CGEvent-backed with deltas.
        injectCGMove(viewToScreen(center), 12, -7, "cg_move_delta_12_-7");
        break;
    case 4:
        injectCGMove(viewToScreen(center), 3, 4, "cg_move_delta_3_4");
        break;
    case 5: // Warp while locked: CGError + CG-side read-back.
        {
            immutable target = screenToCG(viewToScreen(center));
            immutable before = cgPointerLocation();
            immutable err = CGWarpMouseCursorPosition(target);
            immutable after = cgPointerLocation();
            g_arrivalsAtWarp = g_arrivals;
            instr("warp", "target=(%.1f,%.1f) err=%d before=(%.1f,%.1f) after=(%.1f,%.1f)",
                target.x, target.y, err, before.x, before.y, after.x, after.y);
        }
        break;
    case 6: // Did the warp synthesize any motion event? + suppression interval.
        {
            instr("warp_events", "arrivals_since_warp=%d note=warp_generates_no_events_documented",
                g_arrivals - g_arrivalsAtWarp);
            void* src = CGEventSourceCreate(kCGEventSourceStateCombinedSessionState);
            if (src !is null)
            {
                immutable def = CGEventSourceGetLocalEventsSuppressionInterval(src);
                CGEventSourceSetLocalEventsSuppressionInterval(src, 0.0);
                instr("suppression_interval", "default_s=%.3f set_s=0.000 readback_s=%.3f scope=per_event_source",
                    def, CGEventSourceGetLocalEventsSuppressionInterval(src));
                CFRelease(src);
            }
            else
                instr("suppression_interval", "result=source_create_failed");
        }
        break;
    case 7:
        exitLock();
        break;
    case 8: // Display-scoped hide/show, for contrast with NSCursor's app counter.
        {
            immutable did = CGMainDisplayID();
            immutable h = CGDisplayHideCursor(did);
            immutable s = CGDisplayShowCursor(did);
            instr("cursor", "op=CGDisplayHideCursor err=%d display=%u scope=display", h, did);
            instr("cursor", "op=CGDisplayShowCursor err=%d display=%u scope=display", s, did);
        }
        break;
    case 9: // Confine workaround on: center half of the content view.
        {
            immutable rv = confineRectView(b);
            g_confineScreen = NSRect(viewToScreen(rv.origin), rv.size);
            g_confine = true;
            instr("confine", "rect_view=(%.0f,%.0f %.0fx%.0f) rect_screen=(%.0f,%.0f %.0fx%.0f) api=none_public mechanism=warp_back",
                rv.origin.x, rv.origin.y, rv.size.width, rv.size.height,
                g_confineScreen.origin.x, g_confineScreen.origin.y,
                g_confineScreen.size.width, g_confineScreen.size.height);
            g_view.setNeedsDisplay(true);
        }
        break;
    case 10: // Inside: no warp expected.
        injectCGMove(viewToScreen(center), 5, 0, "confine_inside");
        break;
    case 11: // Past the right edge of the confine rect.
        injectCGMove(viewToScreen(NSPoint(b.size.width - 10, center.y)), 40, 0,
            "confine_outside_right");
        break;
    case 12: // Far past the top-left corner.
        injectCGMove(viewToScreen(NSPoint(5, b.size.height - 5)), -60, -50,
            "confine_outside_topleft");
        break;
    case 13:
        injectCGMove(viewToScreen(center), 10, 10, "confine_inside_again");
        break;
    case 14:
        g_confine = false;
        instr("confine", "state=off out_of_bounds_deliveries=%d warps=%d",
            g_outOfBounds, g_warps);
        break;
    case 15:
        stopApp();
        break;
    default:
        break;
    }
    ++g_step;
}

int main()
{
    g_auto = getenv("WSI_AUTO_EXIT") !is null;
    instrInit("APPKIT_F10");
    instr("init_start", "auto_exit=%d", g_auto ? 1 : 0);

    instr("step", "name=CGMainDisplayID");
    if (CGMainDisplayID() == 0)
    {
        printf("SKIP: no macOS window server (CGMainDisplayID == 0)\n");
        return 0;
    }

    auto pool = autoreleasepool_push();
    scope (exit)
        autoreleasepool_pop(pool);

    g_app = NSApplication.sharedApplication();
    g_app.setActivationPolicy(NSApplicationActivationPolicyRegular);

    immutable contentRect = NSRect(NSPoint(120, 120), NSSize(480, 320));
    g_win = NSWindow.alloc().initWithContentRect(contentRect,
        NSWindowStyleMaskTitled | NSWindowStyleMaskClosable | NSWindowStyleMaskResizable,
        NSBackingStoreBuffered, false);
    g_win.setTitle(NSString.alloc().initWithUTF8String("wsi-f10-pointer-capture"));
    g_view = LookView.alloc().initWithFrame(NSRect(NSPoint(0, 0), contentRect.size));
    g_win.setContentView(g_view);
    g_win.makeKeyAndOrderFront(null);
    g_app.activateIgnoringOtherApps(true);
    g_win.makeFirstResponder(g_view);
    g_winNum = g_win.windowNumber();

    // mouseMoved: is opt-in on macOS — without this, only drags arrive.
    immutable beforeOptIn = g_win.acceptsMouseMovedEvents();
    g_win.setAcceptsMouseMovedEvents(true);
    instr("window_created", "win_num=%ld accepts_mouse_moved_default=%d set=1",
        g_winNum, beforeOptIn ? 1 : 0);

    instr("step", "name=script_timer_start interval_ms=150");
    NSTimer.scheduledTimerWithTimeInterval(0.15, g_view, SEL.register("tick:"), null, true);

    instr("step", "name=NSApp_run");
    g_app.run();

    instr("loop_exit", "steps=%d arrivals=%d warps=%d", g_step, g_arrivals, g_warps);
    return 0;
}
