/**
 * Compile-time test discovery.
 *
 * Walks the modules listed by dub's generated `dub_test_root.allModules`,
 * collecting every `unittest` block — module-level and nested in aggregates —
 * into runtime $(REF Test, sparkles,test_runner,model) descriptions, and
 * exposes the attribute metadata needed by the specialized execution modes.
 */
module sparkles.test_runner.discovery;

import std.meta : Alias, AliasSeq, staticMap;
import std.traits : fullyQualifiedName, getUDAs, hasUDA;

import sparkles.test_runner.attributes : benchmark, betterC, ctfe, wasm, workload;
import sparkles.test_runner.model : Test, TestLocation, TestTraits;

/// The module containing `m`: `m` itself when it is a module, or its parent
/// when the module contains a member of the same name (in which case dub's
/// `allModules` yields the member).
template moduleOf(alias m)
{
    static if (__traits(isModule, m))
        alias moduleOf = m;
    else
        alias moduleOf = Alias!(__traits(parent, m));
}

/// The display name of a unittest: its first string UDA, or its identifier.
string testName(alias test)()
{
    foreach (attribute; __traits(getAttributes, test))
        static if (is(typeof(attribute) : string))
            return attribute;
    return __traits(identifier, test);
}

/// The source location of a unittest block.
TestLocation testLocation(alias test)()
{
    auto loc = __traits(getLocation, test);
    return TestLocation(file: loc[0], line: loc[1], column: loc[2]);
}

/// The subset of a test's function attributes that extracted `@betterC` /
/// `@wasm` test functions re-apply (safety, purity, `nothrow`, `@nogc`).
string functionAttributesOf(alias test)()
{
    string attributes;
    static foreach (attribute; __traits(getFunctionAttributes, test))
    {
        static if (attribute == "@safe" || attribute == "@system"
            || attribute == "pure" || attribute == "nothrow" || attribute == "@nogc")
        {
            attributes ~= attribute ~ " ";
        }
    }
    return attributes;
}

/// The runner-attribute traits of a unittest block.
TestTraits testTraits(alias test)()
{
    TestTraits traits;
    traits.isBetterC = hasUDA!(test, betterC);
    traits.isCtfe = hasUDA!(test, ctfe);
    traits.isWasm = hasUDA!(test, wasm);
    static if (hasUDA!(test, betterC) || hasUDA!(test, wasm))
    {
        traits.functionAttributes = functionAttributesOf!test;
        // `@betterC` / `@wasm` attach the type; `@betterC(...)` a value —
        // same shape as `@benchmark` below.
        static foreach (marker; AliasSeq!(betterC, wasm))
            static if (hasUDA!(test, marker))
            {{
                alias uda = Alias!(getUDAs!(test, marker)[0]);
                static if (!is(uda))
                    traits.selfContained |= uda.selfContained;
            }}
    }
    static if (hasUDA!(test, benchmark))
    {
        traits.isBenchmark = true;
        alias uda = Alias!(getUDAs!(test, benchmark)[0]);
        // `@benchmark` attaches the type; `@benchmark(...)` attaches a value.
        static if (!is(uda))
            traits.benchIterations = uda.iterations;
    }
    static if (hasUDA!(test, workload))
    {
        static assert(!hasUDA!(test, benchmark),
            "`@benchmark` and `@workload` are exclusive measurement models: "
            ~ fullyQualifiedName!test);
        traits.isWorkload = true;
        traits.workloadReps = 1;
        alias wuda = Alias!(getUDAs!(test, workload)[0]);
        static if (!is(wuda))
            traits.workloadReps = wuda.reps ? wuda.reps : 1;
    }
    return traits;
}

/// A runtime description of one unittest block.
Test makeTest(alias test)()
{
    return Test(
        fullName: fullyQualifiedName!test,
        name: testName!test,
        location: testLocation!test,
        traits: testTraits!test,
        ptr: &test,
    );
}

/// All `unittest` blocks of `module_` — module-level and nested in structs
/// and classes (the guard chain mirrors the one battle-tested in silly) — as
/// one alias sequence. The `@ctfe` probe generated by
/// $(MREF sparkles,test_runner,extract) inlines a copy of this walk, so the
/// two must agree on what exists.
template moduleUnitTests(alias module_)
{
    private template memberUnitTests(string member)
    {
        static if (__traits(compiles, __traits(getMember, module_, member)) &&
            __traits(compiles, __traits(isTemplate, __traits(getMember, module_, member))) &&
            !__traits(isTemplate, __traits(getMember, module_, member)) &&
            __traits(compiles, __traits(parent, __traits(getMember, module_, member))) &&
            __traits(isSame, __traits(parent, __traits(getMember, module_, member)), module_) &&
            __traits(compiles, __traits(getUnitTests, __traits(getMember, module_, member))))
        {
            alias memberUnitTests =
                AliasSeq!(__traits(getUnitTests, __traits(getMember, module_, member)));
        }
        else
            alias memberUnitTests = AliasSeq!();
    }

    alias moduleUnitTests = AliasSeq!(
        __traits(getUnitTests, module_),
        staticMap!(memberUnitTests, __traits(derivedMembers, module_)));
}

/// All tests declared at module level or inside aggregates of `module_`.
Test[] moduleTests(alias module_)()
{
    Test[] tests;
    static foreach (test; moduleUnitTests!module_)
        tests ~= makeTest!test;
    return tests;
}

/// All tests of the given modules (pass `dub_test_root.allModules`).
Test[] discoverTests(Modules...)()
{
    Test[] tests;
    static foreach (m; Modules)
        tests ~= moduleTests!(moduleOf!m)();
    return tests;
}

version (unittest)
{
    @("discovery.selfTest")
    @betterC(selfContained: true) @safe pure nothrow @nogc
    unittest
    {
        // Discovered by the tests below via reflection on this module.
        // `selfContained`: this module imports std.traits, so it cannot be
        // compiled into the extracted -betterC program.
        assert(1 + 1 == 2);
    }

    /// Hosts an aggregate-nested `@ctfe` test: nested tests must be forced
    /// through CTFE exactly like module-level ones (they used to be reported
    /// as compile-time-verified without ever being executed).
    private struct NestedCtfeHost
    {
        @("discovery.nestedCtfe")
        @ctfe @safe pure nothrow
        unittest
        {
            // Passes only under CTFE — fails loudly if the runner ever
            // executes it at runtime instead of during compilation.
            assert(__ctfe, "nested @ctfe test executed at runtime");
        }
    }
}

version (unittest)
{
    // `testTraits` accepts any annotated symbol; plain private functions keep
    // these fixtures out of consumers' discovered-test lists (a real
    // `@workload` unittest here would surface as a skipped test in every
    // consumer's normal runs).
    @workload(reps: 3) private void workloadRepsFixture() {}
    @workload private void workloadBareFixture() {}
    @workload(reps: 0) private void workloadZeroFixture() {}
    @benchmark @workload private void benchmarkWorkloadClashFixture() {}
}

@("discovery.workloadTraits")
@safe pure nothrow @nogc
unittest
{
    enum reps3 = testTraits!workloadRepsFixture();
    static assert(reps3.isWorkload);
    static assert(reps3.workloadReps == 3);
    static assert(!reps3.isBenchmark);

    enum bare = testTraits!workloadBareFixture();
    static assert(bare.isWorkload);
    static assert(bare.workloadReps == 1);

    // `reps: 0` is clamped at discovery so the driver never sees 0.
    enum zero = testTraits!workloadZeroFixture();
    static assert(zero.workloadReps == 1);

    // The two measurement models are exclusive — combining the markers is a
    // discovery-time error.
    static assert(!__traits(compiles, testTraits!benchmarkWorkloadClashFixture()));
}

@("discovery.moduleTests")
@safe
unittest
{
    alias thisModule = Alias!(__traits(parent, moduleTests));
    enum tests = moduleTests!thisModule();
    static assert(tests.length >= 2);

    enum self = () {
        foreach (t; tests)
            if (t.name == "discovery.selfTest")
                return t;
        assert(0, "discovery.selfTest not found");
    }();
    static assert(self.traits.isBetterC);
    // `@betterC(selfContained: true)` attaches a value rather than the type;
    // both spellings must still register as `@betterC`, and the field has to
    // come through so the driver leaves this module out of the extracted
    // program (it imports std.traits and cannot compile under -betterC).
    static assert(self.traits.selfContained);
    static assert(!self.traits.isCtfe);
    static assert(self.location.file.length > 0);
    static assert(self.location.line > 0);
    assert(self.moduleName == "sparkles.test_runner.discovery");

    // The aggregate-nested @ctfe test is discovered — and therefore also
    // covered by the runner's compile-time forcing, which iterates the same
    // `moduleUnitTests` sequence.
    enum nested = () {
        foreach (t; tests)
            if (t.name == "discovery.nestedCtfe")
                return t;
        assert(0, "discovery.nestedCtfe not found");
    }();
    static assert(nested.traits.isCtfe);
    assert(nested.moduleName == "sparkles.test_runner.discovery.NestedCtfeHost");
}
