name: CI

on:
  # Allow this workflow to be triggered manually:
  workflow_dispatch:

  # Allow this workflow to be run in merge queues:
  merge_group:

  # Run this workflow when PRs target `main` and when they're merged in `main`:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Nix
        uses: metacraft-labs/nixos-modules/.github/setup-nix@main
        with:
          push-to-cache: false
          nix-github-token: ${{ github.token }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          cachix-cache: ${{ vars.CACHIX_CACHE }}
          trusted-public-keys: ${{ vars.TRUSTED_PUBLIC_KEYS }}
          substituters: ${{ vars.SUBSTITUTERS }}

      - name: Restore lychee cache
        id: restore-lychee-cache
        uses: actions/cache/restore@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Check formatting
        run: nix develop --accept-flake-config .#pre-commit -c prek run --all-files --show-diff-on-failure --color always

      - name: Save lychee cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .lycheecache
          key: ${{ steps.restore-lychee-cache.outputs.cache-primary-key }}

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            system: x86_64-linux
            DC: ldc2
          - runner: ubuntu-latest
            system: x86_64-linux
            DC: dmd
          - runner: macos-latest
            system: aarch64-darwin
            DC: ldc2
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Nix
        uses: metacraft-labs/nixos-modules/.github/setup-nix@main
        with:
          push-to-cache: false
          cachix-cache: ${{ vars.CACHIX_CACHE }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          trusted-public-keys: ${{ vars.TRUSTED_PUBLIC_KEYS }}
          substituters: ${{ vars.SUBSTITUTERS }}
          devshell: default

      - name: Run flake checks
        run: nix flake check

      - name: Build and test with dub
        run: ./scripts/run-tests.sh

      - name: Register local package
        run: dub add-local .

      - name: Verify README examples
        run: ./scripts/run_md_examples.d --verify --glob='**/*.md'
